### ISSUE TITLE
Exception thrown in net.rptools.maptool.client.swing.TooltipView.getToolTipText(TooltipView.java:43)

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#1015]
**Describe the bug**
I'll have to research this when I get back due to the holidays.

I click my macro called "Defense Special Conditions" and sometimes this happens:

```
java.lang.NullPointerException
	at net.rptools.maptool.client.swing.TooltipView.getToolTipText(TooltipView.java:43)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getToolTipText(BasicTextUI.java:1325)
	at java.desktop/javax.swing.text.JTextComponent.getToolTipText(JTextComponent.java:1980)
	at java.desktop/javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:675)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:43)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
**To Reproduce**

1. Click my "Defense Special Conditions" macro.
2. Sometimes the above exception occurs.

I'll have to provide a sample *.cmpgn file when I get back from the holidays.

**MapTool Info**

MapTool 1.5.8

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by adventuremagic123** [comment]
I think somehow my macro created this issue.  I made some changes to it and was not able to recreate the problem.

My other macros which I recently tested under MapTool 1.5.8 did NOT show this problem.

I will have to investigate further after the holidays!

**Comment by Phergus** [comment]
Chances are your macro was creating a malformed `href` target.  The error comes from trying to get the href element and getting a null element.

**Comment by Phergus** [comment]
If you can provide a macro that can produces this error. (Just a macro not an entire campaign file.) We can look at catching/reporting the error in MapTool.

**Comment by adventuremagic123** [comment]
This exception is encountered when mousing over hyperlinks (see HTML tag "<a>") in the Chat Window.

**Comment by adventuremagic123** [comment]
The problem seems to reproduce both in the case where h:TempAdjustmentUrl  is "" and when it is "http://www.cnn.com".

**Comment by adventuremagic123** [comment]
This is the exception I get with the above code.  I think it's the same exception I reported for this bug.

```
java.lang.NullPointerException
	at net.rptools.maptool.client.swing.TooltipView.getToolTipText(TooltipView.java:43)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.text.View.getToolTipText(View.java:1051)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getToolTipText(BasicTextUI.java:1325)
	at java.desktop/javax.swing.text.JTextComponent.getToolTipText(JTextComponent.java:1980)
	at java.desktop/javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:675)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:43)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by Phergus** [comment]
Exception caused by incorrectly formed anchor tag having URL instead of HREF in it.

Simple case to produce error:
```
[r: foo = '<a url="">Some text</a>']
```
