### ISSUE TITLE
Change the current campaign file format to a directory

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#102]
Some benefits include
Ability to store database files
Ability to work on macros (both JS and MTScript outside MapTool

**Comment by Darinth** [comment]
Is the interest here in removing the usage of zip files, or just splitting content.xml into multiple small files within the zip?

If we are we talking about entirely eliminating the usage of zip files so that a single campaign is actually multiple files rather than a single zipped file, then while I can see benefits to it, I'd actually disagree with the change on the grounds of 'keeping it simple for the average user'. One of the benefits of a single zip file is that A: users who don't know what they're doing can't make mistakes. B: Transfering the campaign file to another person is trivially easy.

The campaign files are already zip files and should be able to store database information and once you know that the campaign files are just zip files, you can actually open them up and work on macros outside of MT. What might make more sense (at least to me) is to start pulling some of the content out of content.xml (I believe that's the file that contains all of the campaign details) and move some of that into it's own files inside of the zip.

**Comment by kayila** [comment]
I see no solid reason why we can't have the directory format and then zip the folter to get a single file campaign. Both can probably be supported

**Comment by Jaggeroth** [comment]
Yes, I think the desire is to have both. But if you can explode a campaign file into a directory structure then the option of storing said campaign in a source control system becomes a very practical option.

**Comment by Darinth** [comment]
I don't know that I ever would've considered storing a campaign file in a source control system, even though it makes perfect sense and is honestly a compelling reason to have the option of working on maptool campaigns as directories.

It doesn't seem to make a huge amount of sense to be always doing both all of the time, but at a minimum I acknowledge the benefits of having an option to save maptool campaigns into a directory structure over having them zipped.

**Comment by oliver-szymanski** [comment]
Started coding this, will ping when I have a workable/testable solution

**Comment by JamzTheMan** [comment]
I know @cwisniew had done some Proofs on this.

@cwisniew do you have any design requirements for this?

**Comment by oliver-szymanski** [comment]
I got the save/load to work already.

Just need to check how/if to split content to multiple files.

**Comment by kayila** [comment]
I thought the whole point of this was to split the content into different
files?

**Comment by oliver-szymanski** [comment]
Sure, but first I had to start with saving/loading/exporting it as a directory. Works now. 

Now I'm at splitting in files.

**Comment by oliver-szymanski** [comment]
All done, will test it a bit before creating the PR

**Comment by oliver-szymanski** [comment]
PR in https://github.com/RPTools/maptool/pull/371

This enhancement allows you to:
save files as a directory structure instead of a cmpgn (zipped) file
; therefore you use git or another source control system to manage them and you can open/check files with an editor (only experts should do the latter)
split the big content.xml file in multiple files per campaign/zone/token/macros; make it easier when using a source control system to detect/manage changes
puts the actual macro code in a ".macro" plain text file, so you can edit the code easily with any editor if you like
allows to copy whole zones or just tokens or macros between campaigns; e.g. have a base map with all your macros and use that from a linked shared folder. so you can have lots of campaign sharing code

**Comment by JamzTheMan** [comment]
@oliver-szymanski Just got this error:

![image](https://user-images.githubusercontent.com/8051654/54925974-61610d00-4edd-11e9-9d3f-fb5fe877fc53.png)

**Comment by kayila** [comment]
Maybe a little late for this, but... I would suggest naming the macro
endings something like .mtmacro, or .mtm to tie them to maptool as opposed
to having the file format potentially confused with a different .macro
extension. Just my $0.02

**Comment by JamzTheMan** [comment]
Tried another campaign...

> 09:12:31.372 (MapTool.java:300) [SwingWorker-pool-1226169668-thread-2] ERROR net.rptools.maptool.client.MapTool - msg.error.failedSaveCampaign
> java.io.FileNotFoundException: C:\Users\Jamz\.maptool-rptools\tmp\CCFC30077CB0449ABF6C99D6B19E44E9.tmp\zones\C5C22310A34242E18FAF6AECEB381556_0. Camp\tokens\A267BDF7FE3B4534B9CEC83353E63B29_Next grave...\t__Next grave....xml (The system cannot find the path specified)
> 	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
> 	at java.io.FileOutputStream.open(FileOutputStream.java:299) ~[?:?]
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238) ~[?:?]
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:188) ~[?:?]
> 	at net.rptools.lib.io.PackedFile.putFile(PackedFile.java:531) ~[main/:?]
> 	at net.rptools.maptool.util.PersistenceUtil.saveCampaign(PersistenceUtil.java:435) ~[main/:?]
> 	at net.rptools.maptool.client.AppActions$76.doInBackground(AppActions.java:2505) [main/:?]
> 	at org.jdesktop.swingworker.SwingWorker$1.call(Unknown Source) [swing-worker-1.1.jar:?]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
> 	at org.jdesktop.swingworker.SwingWorker.run(Unknown Source) [swing-worker-1.1.jar:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
> 	at java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by JamzTheMan** [comment]
@kayila FYI .mtmacro is already the extension for exported macros. Also I think they are split, a metadata file and the .macro is the actual macro code (so you could more easily edit them outside MapTool if you wanted)

Is there another program that uses .macro?

How about .mtscript?  And then we would have .mtscript2 later as well?  We should probably nail down the names and account for 2.0...

**Comment by oliver-szymanski** [comment]
I can still change it, only the people testing would have a problem with an
already saved campaign, which we can probably deal with.

**Comment by JamzTheMan** [comment]
@oliver-szymanski FYI: I have macros with "labels" like below which may be screwing with the save?

`<img height=78 width=177 src="asset://83074bf79bb6257ba2189061e28e8f70"></img>`

Regarding changes, yes, this is a feature branch, breaking changes are expected. I'm surely not going to use this for my games until it's in a release. Change away.

FYI: In regards to macro labels, I like have "images" for the label but it makes it near impossible to refer to them in a macro (only use them in campaign macros).  I had an idea of adding a macro "name" and leave the "label" for "display purposes only" (Although consideration for backwards compatibility set name to label if blank or leave label as is and create a "display" field or such? I also wanted to add ability to hide/show hotkey on label, but that can be separate.

Maybe this is a good time to do that now? Although we should only allow alpha characters and no spaces, that would break a lot of things unless considerations were taken...

**Comment by Phergus** [comment]
Recommend add a advisory notice when exporting/importing.  Something like the Import Map warning.
![image](https://user-images.githubusercontent.com/34379254/54933330-13023d00-4ee2-11e9-9087-5bc73a377b5a.png)
Something to the effect of:  "This is an **experimental** feature.  It is recommended that you also save campaigns in .cmpgn format for backup purposes."

**Comment by JamzTheMan** [comment]
saving as both is probably not a bad practice while using this feature... Although saving ti GitHub will add some additional revision history...

We should def mark this as experimental as a CYA for at least until we go to the next stable release.

(is it time to remove the experimental feature from export/import?)

**Comment by Phergus** [comment]
Opening issue on the Import Map option.

**Comment by oliver-szymanski** [comment]
changed the macro code file ending to .mtscript as suggested before

**Comment by JamzTheMan** [comment]
@cwisniew I'm thinking as long as we have the "warning message" for this and we can still save to .cmpgn format and open .cmpgn in previous version(s) then we can put this in the next release.

But we should open another issue for 2.0 and mark that as "design required" and start taking notes.

@RPTools/coredevs Any objections?

**Comment by caj-larsson** [comment]
Has there been any discussion or progress on this? Is any help wanted?

**Comment by source-knights** [comment]
I'm using it in my own fork since I implemented it. But as far as I know they want to restructure saves in future versions of Maptool

**Comment by caj-larsson** [comment]
Very happy to hear that it works well, I started looking at merging with current master and there are some, 33, collisions. I'm sure it's easy to fix that tho.

Yeah, the desire to change saves is there but I haven't found what the concrete ideas are yet. I would love to contribute some time to move this along if possible but not sure where to look to.

**Comment by Merudo** [comment]
Are there any changes in @source-knights's fork that shouldn't be merged in develop?

**Comment by source-knights** [comment]
Actually my fork contains more, but there was a specific branch for the directory campaign change. The original PR from Fork was https://github.com/RPTools/maptool/pull/371, and that was merged to campaign-dir branch in MapTool itself https://github.com/RPTools/maptool/tree/campaign-dir

My fork contains more, as a floating windows/button feature, fullscreen mode with UI, various features for macro developers (new events, functions, ...) together with the https://github.com/source-knights/MapTool-jadebringer-extension/tree/v0.0.5

**Comment by cwisniew** [comment]
If anyone wants to look at this its probably worth starting to see what it takes to merge the [campaign-dir](/RPTools/maptool/tree/campaign-dir) into the [develop-2.0](/RPTools/maptool/tree/develop-2.0) branch as this will be a 2.0 feature. 2.0 is planned for after 1.8, but might slip to after another intermediate release (1.9) depending on timing of MTScript 2 development.

There will probably be more conflicts with develop-2.0 than develop and the 2.0 branch has the start of the expanded assets work

**Comment by caj-larsson** [comment]
I took a look at the collisions in the above-mentioned merge. There are mostly GUID management differences and threading differences that seem like a bit of work. Making it merge doesn't look like a horribly hard task but someone that has a lot of experience in the code base will have to look at it I think.

**Comment by source-knights** [comment]
The GUID changes were needed to not lose data or get duplicates when it is
all split in different files. Cause when I remember correctly the original
code was always creating new GUIDs when saving

**Comment by thelsing** [comment]
Is there any merit in doing this? Contents of the campaign files are considered internal and could change in every new release. If we expose them to users there will be tons of users that change something in that directory and MT stops working with this campaign. With the file sync services available today (Dropbox, OneDrive & Co) it's easy to keep a version history there. What changed exactly in the campaign file shouldn't matter to the users.

**Comment by Phergus** [comment]
Some users tend to have 200MB+ and even 500MB campaign files which means synching to the cloud can take just long enough to interfere with any automatic backups from MT.

I do expect that version control of campaign contents is less important for those that have moved their token libs to Add-Ons.

**Comment by thelsing** [comment]
Automatic backups are done in a different directory so this shouldn't be an issue.
