### ISSUE TITLE
Fix Thread Safety Issues with MD5Key

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1253]
**Describe the bug**
MD5Key is not completely thread safe, although it does make some concessions to thread safety and looks like it is intended to be used from multiple threads.

This class should be made thread safe as it currently can be called from more than one thread and this is only going to start occurring more often in the future.

**Comment by Phergus** [comment]
This change appears to be causing a new exception on startup.
```
com.caucho.hessian.io.HessianFieldException: net.rptools.lib.MD5Key.md5Digest: 'java.lang.ThreadLocal$SuppliedThreadLocal' could not be instantiated
	at com.caucho.hessian.io.JavaDeserializer.logDeserializeError(JavaDeserializer.java:590)
	at com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:391)
	at com.caucho.hessian.io.JavaDeserializer.readMap(JavaDeserializer.java:199)
	at com.caucho.hessian.io.JavaDeserializer.readMap(JavaDeserializer.java:141)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1028)
	at com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:387)
	at com.caucho.hessian.io.JavaDeserializer.readMap(JavaDeserializer.java:199)
	at com.caucho.hessian.io.JavaDeserializer.readMap(JavaDeserializer.java:141)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1028)
```
