### ISSUE TITLE
ConnectionException error (server already running) when no server was active

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1331]
**Describe the bug**
User was editing a map and attempted to start a server (to work on VBL) when the map data was lost and the Grasslands default map came up.

**To Reproduce**
Steps to reproduce the behavior (quoted from the user on Discord):
`So all I did was delete all tokens from the map, then all background objects, then change the grid from 140 to 100, then placed down 2 5000x5000jpg background objects, then attempted to start a server to begin doing VBL when it happened`

**Expected behavior**
When starting a server where the previous one has disconnected, it should _work_!  And even if it fails, it should not result in the user losing their work on their map.

**MapTool Info**
- Version: 1.5.13
- Install: Upgrade from 1.5.12

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Home

**Additional context**
```
2020-02-27 17:36:59.878 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2020-02-27 17:36:59.993 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2020-02-27 17:36:59.996 INFO  net.rptools.maptool.client.MapTool - **                              MapTool Started!                              **
2020-02-27 17:36:59.997 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2020-02-27 17:36:59.998 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2020-02-27 17:37:00.000 INFO  net.rptools.maptool.client.MapTool - AppHome System Property: C:\Users\Memphis\.maptool-rptools\logs
2020-02-27 17:37:00.001 INFO  net.rptools.maptool.client.MapTool - Logging to: C:\Users\Memphis\.maptool-rptools\logs/maptool.log
2020-02-27 17:37:00.002 INFO  net.rptools.maptool.client.MapTool - getting MapTool version from manifest: 1.5.13
2020-02-27 17:37:00.003 INFO  net.rptools.maptool.client.MapTool - getting MapTool vendor from manifest:  rptools
2020-02-27 17:37:00.314 INFO  net.rptools.maptool.client.MapTool - MapTool version: 1.5.13
2020-02-27 17:37:00.315 INFO  net.rptools.maptool.client.MapTool - MapTool vendor: rptools
2020-02-27 17:37:07.929 INFO  net.rptools.maptool.client.AppUpdate - Git-Commit-SHA from Manifest: 6d3e25c8fda7bc458c6b962a0a7654455a8bf480
2020-02-27 17:37:09.575 INFO  net.rptools.maptool.client.AppUpdate - target_commitish from GitHub: 6d3e25c8fda7bc458c6b962a0a7654455a8bf480
2020-02-27 17:37:09.576 INFO  net.rptools.maptool.client.AppUpdate - tag_name from GitHub: 1.5.13
2020-02-27 17:37:58.208 INFO  net.rptools.maptool.client.ui.MapToolFrame - Removing the F10 key from the menuBar's InputMap; it did  exist
2020-02-27 17:38:08.395 INFO  net.rptools.maptool.client.AutoSaveManager - Restarting autosave manager; interval in seconds is 300
2020-02-27 17:40:23.414 INFO  net.rptools.maptool.client.AutoSaveManager - Restarting autosave manager; interval in seconds is 300
2020-02-27 17:42:51.388 INFO  net.rptools.maptool.client.TransferableHelper - Selected: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-file-list;representationclass=java.util.List]
2020-02-27 17:42:58.871 INFO  net.rptools.maptool.client.TransferableHelper - Selected: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-file-list;representationclass=java.util.List]
2020-02-27 17:43:34.685 INFO  net.rptools.maptool.client.TransferableHelper - Selected: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-file-list;representationclass=java.util.List]
2020-02-27 17:45:23.631 INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 212
2020-02-27 17:45:23.634 INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
2020-02-27 17:46:11.150 ERROR net.rptools.maptool.client.MapTool - Server has disconnected.
2020-02-27 17:46:11.771 INFO  net.rptools.maptool.util.UPnPUtil - UPnP:  Trying interface Realtek PCIe GBE Family Controller
2020-02-27 17:46:16.975 INFO  net.rptools.maptool.util.UPnPUtil - UPnP:  Found IGD: DPC3848
2020-02-27 17:46:16.980 INFO  net.rptools.maptool.util.UPnPUtil - Found 1 IGDs on interface Realtek PCIe GBE Family Controller
2020-02-27 17:46:17.275 INFO  net.rptools.maptool.util.UPnPUtil - IP address 192.168.0.34 on interface Realtek PCIe GBE Family Controller
2020-02-27 17:46:18.999 INFO  net.rptools.maptool.util.UPnPUtil - UPnP: Port 51234 mapped on Realtek PCIe GBE Family Controller at address 192.168.0.34
2020-02-27 17:46:19.002 ERROR net.rptools.maptool.client.MapTool - msg.error.alreadyRunningServer
2020-02-27 17:46:23.183 ERROR net.rptools.maptool.client.MapTool - msg.error.failedConnect
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:?]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225) ~[?:?]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:148) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402) ~[?:?]
	at java.net.Socket.connect(Socket.java:591) ~[?:?]
	at java.net.Socket.connect(Socket.java:540) ~[?:?]
	at java.net.Socket.<init>(Socket.java:436) ~[?:?]
	at java.net.Socket.<init>(Socket.java:213) ~[?:?]
	at net.rptools.clientserver.simple.client.ClientConnection.<init>(ClientConnection.java:38) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.clientserver.hessian.client.ClientConnection.<init>(ClientConnection.java:28) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.MapToolConnection.<init>(MapToolConnection.java:28) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.MapTool.createConnection(MapTool.java:1143) [MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.AppActions$59$1.run(AppActions.java:2138) [MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.AppActions$ClientAction$1.run(AppActions.java:3160) [MapTool-1.5.13.jar:1.5.13]
2020-02-27 17:46:25.031 ERROR net.rptools.maptool.client.MapTool - msg.error.alreadyRunningServer
2020-02-27 17:46:27.843 ERROR net.rptools.maptool.client.MapTool - msg.error.failedStartPersonalServer
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:?]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225) ~[?:?]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:148) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402) ~[?:?]
	at java.net.Socket.connect(Socket.java:591) ~[?:?]
	at java.net.Socket.connect(Socket.java:540) ~[?:?]
	at java.net.Socket.<init>(Socket.java:436) ~[?:?]
	at java.net.Socket.<init>(Socket.java:213) ~[?:?]
	at net.rptools.clientserver.simple.client.ClientConnection.<init>(ClientConnection.java:38) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.clientserver.hessian.client.ClientConnection.<init>(ClientConnection.java:28) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.MapToolConnection.<init>(MapToolConnection.java:28) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.MapTool.createConnection(MapTool.java:1143) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.MapTool.startPersonalServer(MapTool.java:1131) [MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.AppActions$59$1.run(AppActions.java:2173) [MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.AppActions$ClientAction$1.run(AppActions.java:3160) [MapTool-1.5.13.jar:1.5.13]
2020-02-27 17:47:07.875 INFO  net.rptools.maptool.client.AutoSaveManager - Autosave complete.  Elapsed time (ms): 104,239
2020-02-27 17:47:07.876 INFO  net.rptools.maptool.client.AutoSaveManager - Restarting autosave manager; interval in seconds is 300
2020-02-27 17:47:11.196 INFO  net.rptools.maptool.client.AutoSaveManager - Restarting autosave manager; interval in seconds is 300
2020-02-27 17:48:07.426 INFO  net.rptools.maptool.client.TransferableHelper - Selected: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-file-list;representationclass=java.util.List]
2020-02-27 17:48:11.999 INFO  net.rptools.maptool.client.TransferableHelper - Selected: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-file-list;representationclass=java.util.List]
2020-02-27 17:48:34.691 INFO  net.rptools.maptool.util.UPnPUtil - UPnP: Port unmapped from Realtek PCIe GBE Family Controller
2020-02-27 17:48:34.693 ERROR net.rptools.maptool.client.MapTool - Server has disconnected.
2020-02-27 17:48:35.173 INFO  net.rptools.maptool.util.UPnPUtil - UPnP:  Trying interface Realtek PCIe GBE Family Controller
2020-02-27 17:48:40.192 INFO  net.rptools.maptool.util.UPnPUtil - UPnP:  Found IGD: DPC3848
2020-02-27 17:48:40.192 INFO  net.rptools.maptool.util.UPnPUtil - Found 1 IGDs on interface Realtek PCIe GBE Family Controller
2020-02-27 17:48:40.385 INFO  net.rptools.maptool.util.UPnPUtil - IP address 192.168.0.34 on interface Realtek PCIe GBE Family Controller
2020-02-27 17:48:41.827 INFO  net.rptools.maptool.util.UPnPUtil - UPnP: Port 51234 mapped on Realtek PCIe GBE Family Controller at address 192.168.0.34
2020-02-27 17:48:41.829 ERROR net.rptools.maptool.client.MapTool - msg.error.alreadyRunningServer
2020-02-27 17:48:44.666 INFO  net.rptools.maptool.util.UPnPUtil - UPnP: Port unmapped from Realtek PCIe GBE Family Controller
2020-02-27 17:48:44.927 ERROR net.rptools.maptool.client.MapTool - msg.error.failedConnect
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:?]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225) ~[?:?]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:148) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402) ~[?:?]
	at java.net.Socket.connect(Socket.java:591) ~[?:?]
	at java.net.Socket.connect(Socket.java:540) ~[?:?]
	at java.net.Socket.<init>(Socket.java:436) ~[?:?]
	at java.net.Socket.<init>(Socket.java:213) ~[?:?]
	at net.rptools.clientserver.simple.client.ClientConnection.<init>(ClientConnection.java:38) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.clientserver.hessian.client.ClientConnection.<init>(ClientConnection.java:28) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.MapToolConnection.<init>(MapToolConnection.java:28) ~[MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.MapTool.createConnection(MapTool.java:1143) [MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.AppActions$59$1.run(AppActions.java:2138) [MapTool-1.5.13.jar:1.5.13]
	at net.rptools.maptool.client.AppActions$ClientAction$1.run(AppActions.java:3160) [MapTool-1.5.13.jar:1.5.13]
```

**Comment by Azhrei** [comment]
This is a strange one.  The `START_SERVER` action only enables the menu option for starting a server when `MapTool.isPersonalServer()` is true.  And it checks inside the thread to ensure that it's still true before it continues.  Yet the log messages (timestamp `17:46:19.002`, for example) indicates that this guard condition was violated.  I don't see how this is possible unless another thread changed it...

**Comment by Phergus** [comment]
To start a "real" server, the personal server has to stop doesn't it?  Perhaps the personal server was able to shutdown and clear that flag too fast?

**Comment by cwisniew** [comment]
> This is a strange one. The START_SERVER action only enables the menu option for starting a server when MapTool.isPersonalServer() is true. **And it checks inside the thread** to ensure that it's still true before it continues. Yet the log messages (timestamp 17:46:19.002, for example) indicates that this guard condition was violated. I don't see how this is possible unless another thread changed it...

> **And it checks inside the thread** 
Therein lies the potential problem, MapTool.isPersonalServer() is not thread safe. Which means it is quite possible for the Swing EDT to see it set to one value and the background thread to see it set to another (say the default value on initialisation) no concurrent modification is required to cause this problem.

**Comment by Azhrei** [comment]
Yep, that's pretty clear.  But what other thread is calling that function and changing its state?

**Comment by cwisniew** [comment]
> Yep, that's pretty clear. But what other thread is calling that function and changing its state?

Suggest you read my comment carefully

**Comment by Azhrei** [comment]
So...  Thread 1 is on the Swing EDT.  It checks to verify that the value is True and it is.  It creates Thread 2 and then goes into an idle state (since there's nothing else to do on the EDT).

Thread 2 wakes up and checks and sees False.

In another discussion you pointed out that instruction reordering could affect what Thread 2 sees.  Yep, no problem.  But prior to Thread 2 starting, the values of the variables in isPersonalServer() were already set.  Absent any thread trying to change those values, all threads should receive True.

Are you saying that creating a Thread doesn't cause a memory barrier to be executed?

If this is going to cause you consternation, please let someone else explain it.  I really do want to understand.

**Comment by cwisniew** [comment]
> Are you saying that creating a Thread doesn't cause a memory barrier to be executed?
> 

Yes, this is what I have been saying in the previous situations and what they examples provided describe.

**Comment by Azhrei** [comment]
I want to be clear:  I agree that isPersonalServer() should have synchronization.  Or rather, that synchronization is needed to correct this problem.  (I don't know that just fixing isPersonalServer() is sufficient; there could be other problems, this is just the first one that jumped out at me.) 

I presume you know who Doug Lea is?  From an excerpt of his book, _Concurrent Programming In Java_:

> Thread.start has the same memory effects as a lock release by the thread calling start, followed by a lock acquire by the started thread.

See [his page](http://gee.cs.oswego.edu/dl/cpj/jmm.html) for more of the excerpt and the following quoted sections.

Assuming that you're not going to argue with his above assertion, starting a thread _does_ implement a memory barrier.  I do not understand why you said it did not In your last post; can you explain that to me, please?

He states elsewhere in that excerpt:

> releasing a lock forces a flush of all writes from working memory employed by the thread

Therefore, all writes to the MapTool object in regards to state variables must be written before Thread 2 can begin.  He also says:

> acquiring a lock forces a (re)load of the values of accessible fields

This means that in my example, above, Thread 2 cannot see a result different from Thread 1 _unless someone changes it_.

So my first question to you remains:  who changed it?  Thread 1 did not, since the EDT is idle.  No other threads within MT will be changing the relevant state variables of the MapTool class such that it could appear to return a different value.  Maybe you know of a thread that _does_ and I'm just not remembering it — which thread is it?

**Comment by cwisniew** [comment]
> I want to be clear: I agree that isPersonalServer() should have synchronization. Or rather, that synchronization is needed to correct this problem. (I don't know that just fixing isPersonalServer() is sufficient; there could be other problems, this is just the first one that jumped out at me.)
> 

It won't be, you must protect every access the mutable state, not just one (more info below). And in this case it's more involved since you have a checkX and do something if X is true/not true the whole bit of logic needs to be tied up in a lock, e.g.  MapTool.startPersonalServerIfNotRunning() which shares the same lock with with setServer(), isHostingSever(), isPersonalServer() etc etc). 


There is a lot of funkiness in the code involved here and there are all sort of places synchronization issues can creep in.


> I presume you know who Doug Lea is? From an excerpt of his book, _Concurrent Programming In Java_:
> 
> > Thread.start has the same memory effects as a lock release by the thread calling start, followed by a lock acquire by the started thread.
> 
> See [his page](http://gee.cs.oswego.edu/dl/cpj/jmm.html) for more of the excerpt and the following quoted sections.
> 
> Assuming that you're not going to argue with his above assertion, starting a thread _does_ implement a memory barrier. I do not understand why you said it did not In your last post; can you explain that to me, please?
> 
> He states elsewhere in that excerpt:
> 
> > releasing a lock forces a flush of all writes from working memory employed by the thread
> 

Ok but it's not that clear cut above is a nice example where there are only 2 threads involved accessing mutable state. In MT when it comes to server disconnection and starting a new server (depending how it happens) there could be 4... Especially if user was connected to a server, got booted, started doing something then tried to start a server. And this is the easiest case to imagine this error happening (not saying only, just easiest to imagine).



The server disconnect occurs in Thread X, and sets it to a Personal Server 
Lets call the EDT thread Thread Y which has its own state it can see
Then there is the new thread you create on Thread Y lets call that thread Z


Which value of the variable does Z pick up when it comes to read it? The effect of releasing and acquiring a lock between Y/Z does not mean that by the time thread Z comes to read the value it will be the same as what thread Y saw it, at some point (and its left intentionally vague) the termination of thread X will be visible to other threads and so will all the values it updated, it could certainly happen at the most inconvenient of times.

To think of it another way, for a change to be visible in another thread it has to happen before a lock release in the initial thread, and the read after a lock acquire in the subsequent thread. So in the case of the Thread.start() you have effectively a thread release/lock but only between 2 of the three threads that are sharing the state. Thread X did its thing with no lock involved so unhappiness ensues as there is now a race condition. 

Thread safety is like pregnancy in that you either are or aren't there are no in betweens, a memory barrier between two things does not mean one between everything.


> Therefore, all writes to the MapTool object in regards to state variables must be written before Thread 2 can begin. He also says:

As above that only holds for the 2 thread case. Server disconnects from remote servers don't happen on EDT.

> 
> > acquiring a lock forces a (re)load of the values of accessible fields
> 
> This means that in my example, above, Thread 2 cannot see a result different from Thread 1 _unless someone changes it_.

Not to belabour the point but just so it's clear for anyone reading the shared state happens between 2 of the 4 threads involved only, so all (well ok many) bets are off.  


> 
> So my first question to you remains: who changed it? Thread 1 did not, since the EDT is idle. No other threads within MT will be changing the relevant state variables of the MapTool class such that it could appear to return a different value. Maybe you know of a thread that _does_ and I'm just not remembering it — which thread is it?

The thread that detects the server disconnection.

The important thing to keep in mind is to be thread safe **ALL** access to state must be done in a thread safe way and this applies to all updates not just those which may be concurrent. 


It's also very possible for a second thread to create a new personal server (one for send and one for receive) and cause the problem -- in fact if I had to make a bet I would bet both things are happening and causing problems but because they are both race conditions you won't see it all the time not would it be easy to identify that only one of them is doing it.

**Comment by Azhrei** [comment]
Ahhh, a separate thread handling the server disconnect...  Yep, that would do it and that’s the answer I was looking for.

I thought the connection between the front end and the server would detect a disconnection only when it attempted to use the network (there is no heartbeat from client to server, only server to registry).  Without special handling, that’s how it’s normally done.

But if there’s a thread monitoring the connection, then it could definitely be setting the state on the MapTool class variables.
