### ISSUE TITLE
NPE when pressing delete key with open Draw Explorer that shows no elements 

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1788]
**Describe the bug**

Open the draw explorer, check that there's no element shown (no drawings), press delete, observer error message

```
java.lang.NullPointerException
	at net.rptools.maptool.client.ui.MapToolFrame$KeyListenerDeleteDraw$1.run(MapToolFrame.java:257)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:313)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:96)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**To Reproduce**

see above

**Expected behavior**

no error

**Screenshots**

see above

**MapTool Info**
- Version: develop (~1.7)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

n/a

**Comment by Phergus** [comment]
Testing.  No longer throws NPE but it does ask if you want to delete the selected drawings which is a bit confusing since there aren't any.

![image](https://user-images.githubusercontent.com/34379254/81486901-79950800-9215-11ea-99c5-be50f34c292c.png)

**Comment by nmeier** [comment]
yeah, that doesn't make sense. I had the prompt off - will push a change.

**Comment by Phergus** [comment]
I figured as much.

**Comment by Phergus** [comment]
@nmeier   PR?  .If you do it, I can review and merge. If I do it, it has to wait for someone else.

**Comment by nmeier** [comment]
PR out now https://github.com/RPTools/maptool/pull/1794

**Comment by Phergus** [comment]
Tested.  No longer shows confirmation dialog.
