### ISSUE TITLE
More useful NullPointerException messages

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1882]
**Is your feature request related to a problem? Please describe.**
With the recent update to Java 14, it is now possible to take advantage of more detailed NullPointerException messages.

For example, instead of

```
Exception in thread "main" java.lang.NullPointerException 
at com.baeldung.java14.npe.HelpfulNullPointerException.main(HelpfulNullPointerException.java:10)
```

we could get

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.baeldung.java14.npe.HelpfulNullPointerException$PersonalDetails.getEmailAddress()" is null
at com.baeldung.java14.npe.HelpfulNullPointerException.main(HelpfulNullPointerException.java:10)
```

**Describe the solution you'd like**
The expended NPE messages need to be enabled for them to work. We should do so.

**Comment by Phergus** [comment]
Creating an NPE via an action such as `[r: getToken(1A)]`  (invalid argument) now produces:
```
java.lang.NullPointerException: Cannot invoke "antlr.collections.AST.equalsTree(antlr.collections.AST)" because "this.tree" is null error executing expression getToken(1A).
Error trace : chat
```
providing more information about what went wrong.
