### ISSUE TITLE
Error / exception messages not working properly 

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1886]
**Is your feature request related to a problem? Please describe.**
Since updating the JIDE framework, the error messages are no longer properly displayed.

Instead, an error message related to the JIDE framework is displayed in a `JOptionPane`.

**Describe the solution you'd like**
The error messages are displayed properly.

**Additional context**

This is caused by `optionPane.setDetailsVisible()` in ` displayPopup` throwing a `ClassCastException`:
```
java.lang.ClassCastException: class javax.swing.plaf.basic.BasicOptionPaneUI cannot be cast to class com.jidesoft.plaf.basic.BasicJideOptionPaneUI (javax.swing.plaf.basic.BasicOptionPaneUI is in module java.desktop of loader 'bootstrap'; com.jidesoft.plaf.basic.BasicJideOptionPaneUI is in unnamed module of loader 'app')
        at com.jidesoft.dialog.JideOptionPane.setDetailsVisible(JideOptionPane.java:157) ~[jide-common-3.7.9.jar:?]
        at net.rptools.maptool.client.swing.MapToolEventQueue.displayPopup(MapToolEventQueue.java:91) ~[main/:?]
        at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:72) [main/:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

For comparison:

Current on develop:

![image](https://user-images.githubusercontent.com/7371085/82346988-bce13a80-99bc-11ea-9256-32d6120e0b5b.png)

On 1.7:

![image](https://user-images.githubusercontent.com/7371085/82347916-d636b680-99bd-11ea-8156-bd00caa60a37.png)

**Comment by Merudo** [comment]
Seems like the folks at T3 had the same error at one point: https://groups.google.com/forum/#!topic/t3-discussion/3dgilvxIcOc

**Comment by Phergus** [comment]
That's funny.  I guess T3 is/was a fork of MapTool?

**Comment by Merudo** [comment]
Yep, but it hasn't been updated since 2014.

I found out the problem: the `JideOptionPane` for the error dialog is set before `Jide` is properly configured.

**Comment by Merudo** [comment]
PR #1887 fixes this.
