### ISSUE TITLE
Bug: moveTokenToMap in onTokenMove gives NPE to players

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#2023]
**Describe the bug**
If a player moves a token on a FoW enabled map and that token triggers a `onTokenMove` which changes the map of the token, it gives a NPE.

**To Reproduce**
1. Created two maps, here named "Map1" and "Map2".
2. Add the following `onTokenMove` macro: `[h: moveTokenToMap(currentToken(), "Map2")]`
3. On Map1, have a token and FoW enabled.
4. Start the server as a player, making sure FoW reveal on move is enabled.
5. Move the token and see the NPE.

**Expected behavior**
No NPE.

**Error Trace***
```
java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.model.Token.isOwner(String)" because "token" is null
	at net.rptools.maptool.client.AppUtil.playerOwns(AppUtil.java:234)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.getOwnedTokens(ZoneRenderer.java:3782)
	at net.rptools.maptool.client.tool.PointerTool.exposeFoW(PointerTool.java:284)
	at net.rptools.maptool.client.tool.PointerTool.stopTokenDrag(PointerTool.java:255)
	at net.rptools.maptool.client.tool.PointerTool.mouseReleased(PointerTool.java:599)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**MapTool Info**
- Version: 1.7, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Campaign**

[TELEPORT-EXCEPTIONS.cmpgn.zip](https://github.com/RPTools/maptool/files/4789444/TELEPORT-EXCEPTIONS.cmpgn.zip)

**Comment by Merudo** [comment]
PR #2024 fixes this.

**Comment by Phergus** [comment]
Tested.  No longer causes an exception for this case.
