### ISSUE TITLE
NPE on cancel out of "Rename Macro Group..."

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2046]
**Describe the bug**
Cancel out of "Rename Macro Group..." dialog produces NPE

**To Reproduce**
1. Go to selected panel
2. Right Click on macro group, select "Rename Macro Group..."
3. Click Cancel

**Expected behavior**
No change

java.lang.NullPointerException
	at net.rptools.maptool.client.ui.macrobuttons.buttongroups.ButtonGroupPopupMenu$RenameGroupAction.actionPerformed(ButtonGroupPopupMenu.java:647)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:58)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**MapTool Info**
- Version: 1.7.0

**Desktop (please complete the following information):**
 - OS: Win 10

**Additional context**
Gather Debug Information...

==== MapTool Information ====
MapTool Version: 1.7.0
MapTool Home...: C:\Users\Strat\.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 305 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\MapTool_1.7.0\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PATH...........: C:\MapTool_1.7.0\app;C:\MapTool_1.7.0
Number of Procs: 8

==== User Information ====
User Name: Strat
User Home: C:\Users\Strat
User Dir.: C:\MapTool_1.7.0\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Intel(R) Dual Band Wireless-AC 8265
Interface Name: wlan2
Address...: 10.1.1.101
Address...: fe80:0:0:0:6d18:7c48:3ff2:3992%wlan2

Host Address...: 10.1.1.101
Default Gateway: 10.1.1.1

==== Locale Information ====
Country.: Australia
Language: 
Locale..: Australia
Variant.: 

==== Encoding Information ====
Default Locale:   _AU
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

==== Internet Gateway Devices ====
Device Name.: Archer_VR1600v
Model Name..: Archer_VR1600v
Manufacturer: TP-Link
Model Number: 2.0
Model Desc..: AC1600 Wireless Dual Band Gigabit VoIP VDSL/ADSL Modem Router
Firmware....: Linux/3.4.11-rt19, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
External IP.: 103.129.157.34

**Comment by ebudai** [comment]
I will work on this.

**Comment by Phergus** [comment]
Tested.  No longer throws NPE when rename is cancelled.
