### ISSUE TITLE
Nothing drawn (buttons work)

### ISSUE THREAD

**Issue by Duckxz** [RPTools/maptool#2090]
**Describe the bug**
MapTool does not draw anything however UI functionality works (clickables,update notice and popup to confirm save on exit)

**To Reproduce**
1. Download deb
2. Extract .deb file
3. Extract data.tar.xz 
4. go to data/opt/MapTool
5. run ./MapTool

**Expected behavior**
MapTool should be visible

**Screenshots**
![maptool1](https://user-images.githubusercontent.com/49942153/87321379-74fa1200-c52c-11ea-8455-e33b4b1c9b00.png)

**MapTool Info**
- Version(s): 1.5.14 and 1.7.0
- Install: From deb

**Desktop (please complete the following information):**
 - OS: Void Linux

**Additional context**

From MapTool, paste info from menu Help -> Gather Debug Information...
You can also attach files (drag and drop here) such as log files or paste a file sharing link.
[log.txt](https://github.com/RPTools/maptool/files/4913400/log.txt)
(this log is not acquired trough Gather Debug Information)

**Comment by Ceyyec** [comment]
same here with different logs:

`2023-09-24 22:35:36.663 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2023-09-24 22:35:36.720 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2023-09-24 22:35:36.721 INFO  net.rptools.maptool.client.MapTool - **                              MapTool Started!                              **
2023-09-24 22:35:36.721 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2023-09-24 22:35:36.721 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2023-09-24 22:35:36.722 INFO  net.rptools.maptool.client.MapTool - Logging to: /home/cihan/.maptool-rptools/logs/maptool.log
2023-09-24 22:35:36.722 INFO  net.rptools.maptool.client.MapTool - getting MapTool version from manifest: 1.13.2
2023-09-24 22:35:36.723 INFO  net.rptools.maptool.client.MapTool - getting MapTool vendor from manifest:  RPTools
2023-09-24 22:35:36.782 INFO  net.rptools.maptool.client.MapTool - argument passed via command line: -v=1.13.2
2023-09-24 22:35:36.782 INFO  net.rptools.maptool.client.MapTool - overriding MapTool version from command line to: 1.13.2
2023-09-24 22:35:36.782 INFO  net.rptools.maptool.client.MapTool - MapTool vendor: RPTools
2023-09-24 22:35:37.829 INFO  net.rptools.maptool.client.AppUpdate - Implementation-Version from Manifest: 1.13.2
2023-09-24 22:35:37.830 INFO  net.rptools.maptool.client.AppUpdate - Cleaned version: 1.13.2
2023-09-24 22:35:38.881 INFO  net.rptools.maptool.client.ui.MapToolFrame - Removing the F10 key from the menuBar's InputMap; it did  exist
2023-09-24 22:35:38.990 ERROR net.rptools.maptool.client.swing.AbeillePanel - Could not init method: initImportButton
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.rptools.maptool.client.swing.AbeillePanel.panelInit(AbeillePanel.java:99) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.lookuptable.LookupTablePanel.<init>(LookupTablePanel.java:48) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.getLookupTablePanel(MapToolFrame.java:730) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.initializeFrames(MapToolFrame.java:651) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.configureDocking(MapToolFrame.java:540) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.<init>(MapToolFrame.java:451) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.MapTool.initialize(MapTool.java:665) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.MapTool.lambda$main$9(MapTool.java:1788) ~[MapTool.jar:1.13.2]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:?]
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54) [MapTool.jar:1.13.2]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: java.io.IOException: Could not load image 
	at net.rptools.maptool.client.ui.theme.RessourceManager.lambda$getIcon$6(RessourceManager.java:486) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getFromHashMapsAndCache(RessourceManager.java:520) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:470) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:450) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getSmallIcon(RessourceManager.java:457) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.lookuptable.LookupTablePanel.initImportButton(LookupTablePanel.java:225) ~[MapTool.jar:1.13.2]
	... 26 more
Caused by: java.io.IOException: Could not load image 
	at net.rptools.lib.image.ImageUtil.bytesToImage(ImageUtil.java:314) ~[MapTool.jar:1.13.2]
	at net.rptools.lib.image.ImageUtil.getImage(ImageUtil.java:98) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.lambda$getIcon$6(RessourceManager.java:480) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getFromHashMapsAndCache(RessourceManager.java:520) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:470) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:450) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getSmallIcon(RessourceManager.java:457) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.lookuptable.LookupTablePanel.initImportButton(LookupTablePanel.java:225) ~[MapTool.jar:1.13.2]
	... 26 more
2023-09-24 22:35:38.996 ERROR net.rptools.maptool.client.swing.AbeillePanel - Could not init method: initExportButton
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.rptools.maptool.client.swing.AbeillePanel.panelInit(AbeillePanel.java:99) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.lookuptable.LookupTablePanel.<init>(LookupTablePanel.java:48) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.getLookupTablePanel(MapToolFrame.java:730) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.initializeFrames(MapToolFrame.java:651) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.configureDocking(MapToolFrame.java:540) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.MapToolFrame.<init>(MapToolFrame.java:451) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.MapTool.initialize(MapTool.java:665) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.MapTool.lambda$main$9(MapTool.java:1788) ~[MapTool.jar:1.13.2]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:?]
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54) [MapTool.jar:1.13.2]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: java.io.IOException: Could not load image 
	at net.rptools.maptool.client.ui.theme.RessourceManager.lambda$getIcon$6(RessourceManager.java:486) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getFromHashMapsAndCache(RessourceManager.java:520) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:470) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:450) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getSmallIcon(RessourceManager.java:457) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.lookuptable.LookupTablePanel.initExportButton(LookupTablePanel.java:269) ~[MapTool.jar:1.13.2]
	... 26 more
Caused by: java.io.IOException: Could not load image 
	at net.rptools.lib.image.ImageUtil.bytesToImage(ImageUtil.java:314) ~[MapTool.jar:1.13.2]
	at net.rptools.lib.image.ImageUtil.getImage(ImageUtil.java:98) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.lambda$getIcon$6(RessourceManager.java:480) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getFromHashMapsAndCache(RessourceManager.java:520) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:470) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getIcon(RessourceManager.java:450) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.theme.RessourceManager.getSmallIcon(RessourceManager.java:457) ~[MapTool.jar:1.13.2]
	at net.rptools.maptool.client.ui.lookuptable.LookupTablePanel.initExportButton(LookupTablePanel.java:269) ~[MapTool.jar:1.13.2]
	... 26 more
2023-09-24 22:35:39.350 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User sent: CLIENT_INIT_MSG
2023-09-24 22:35:39.395 INFO  net.rptools.maptool.server.ServerHandshake - from 127.0.0.1-0 got: CLIENT_INIT_MSG
2023-09-24 22:35:39.405 INFO  net.rptools.maptool.server.ServerHandshake - Server sent to 127.0.0.1-0: USE_AUTH_TYPE_MSG
2023-09-24 22:35:39.407 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User got: USE_AUTH_TYPE_MSG
2023-09-24 22:35:39.409 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User sent: CLIENT_AUTH_MESSAGE
2023-09-24 22:35:39.410 INFO  net.rptools.maptool.server.ServerHandshake - from 127.0.0.1-0 got: CLIENT_AUTH_MESSAGE
2023-09-24 22:35:39.428 INFO  net.rptools.maptool.server.ServerHandshake - Server sent to 127.0.0.1-0: CONNECTION_SUCCESSFUL_MSG
2023-09-24 22:35:39.430 INFO  net.rptools.maptool.server.ClientHandshake - Anonymous User got: CONNECTION_SUCCESSFUL_MSG
2023-09-24 22:35:39.487 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server sent to 127.0.0.1-0: PLAYER_CONNECTED_MSG
2023-09-24 22:35:39.487 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server broadcast: PLAYER_CONNECTED_MSG
2023-09-24 22:35:39.521 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User got: PLAYER_CONNECTED_MSG
2023-09-24 22:35:39.523 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User handled: PLAYER_CONNECTED_MSG
2023-09-24 22:35:39.523 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User got: PLAYER_CONNECTED_MSG
2023-09-24 22:35:39.523 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User handled: PLAYER_CONNECTED_MSG
2023-09-24 22:35:39.643 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server sent to 127.0.0.1-0: SET_CAMPAIGN_MSG
2023-09-24 22:35:39.658 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User got: SET_CAMPAIGN_MSG
2023-09-24 22:35:39.659 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User handled: SET_CAMPAIGN_MSG
2023-09-24 22:40:40.050 INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 1
2023-09-24 22:40:40.052 INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
2023-09-24 22:40:40.139 INFO  net.rptools.maptool.client.AutoSaveManager - Autosave complete.  Elapsed time (ms): 87
2023-09-24 22:45:40.307 INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 0
2023-09-24 22:45:40.308 INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
2023-09-24 22:45:40.349 INFO  net.rptools.maptool.client.AutoSaveManager - Autosave complete.  Elapsed time (ms): 41
2023-09-24 22:46:03.329 ERROR net.rptools.maptool.server.MapToolServer - Error sending heart beat
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) [okhttp-4.9.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2023-09-24 22:50:40.508 INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 0
2023-09-24 22:50:40.510 INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
2023-09-24 22:50:40.532 INFO  net.rptools.maptool.client.AutoSaveManager - Autosave complete.  Elapsed time (ms): 22
2023-09-24 22:55:40.678 INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 1
2023-09-24 22:55:40.680 INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
2023-09-24 22:55:40.703 INFO  net.rptools.maptool.client.AutoSaveManager - Autosave complete.  Elapsed time (ms): 24
2023-09-24 22:56:15.546 ERROR net.rptools.maptool.server.MapToolServer - Error sending heart beat
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.9.3.jar:?]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) [okhttp-4.9.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2023-09-24 22:56:32.894 ERROR net.rptools.maptool.util.MapToolSysInfoProvider - java.io.IOException: Cannot run program "netstat": error=2, No such file or directory
2023-09-24 22:57:05.446 INFO  net.rptools.maptool.client.MapToolConnection - Anonymous User sent REMOVE_ZONE_MSG
2023-09-24 22:57:05.447 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 got: REMOVE_ZONE_MSG
2023-09-24 22:57:05.448 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server broadcast: REMOVE_ZONE_MSG except to 127.0.0.1-0
2023-09-24 22:57:05.449 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 handled: REMOVE_ZONE_MSG
2023-09-24 22:57:05.451 INFO  net.rptools.maptool.client.MapToolConnection - Anonymous User sent PUT_ZONE_MSG
2023-09-24 22:57:05.452 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 got: PUT_ZONE_MSG
2023-09-24 22:57:05.453 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server broadcast: PUT_ZONE_MSG except to 127.0.0.1-0
2023-09-24 22:57:05.453 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 handled: PUT_ZONE_MSG
2023-09-24 22:57:31.113 INFO  net.rptools.maptool.client.MapToolConnection - Anonymous User sent CLEAR_ALL_DRAWINGS_MSG
2023-09-24 22:57:31.114 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 got: CLEAR_ALL_DRAWINGS_MSG
2023-09-24 22:57:31.114 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server broadcast: CLEAR_ALL_DRAWINGS_MSG
2023-09-24 22:57:31.115 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 handled: CLEAR_ALL_DRAWINGS_MSG
2023-09-24 22:57:31.115 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User got: CLEAR_ALL_DRAWINGS_MSG
2023-09-24 22:57:31.115 INFO  net.rptools.maptool.client.ClientMessageHandler - Anonymous User handled: CLEAR_ALL_DRAWINGS_MSG
2023-09-24 22:57:42.865 INFO  net.rptools.maptool.client.MapToolConnection - Anonymous User sent UPDATE_CAMPAIGN_MSG
2023-09-24 22:57:42.874 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 got: UPDATE_CAMPAIGN_MSG
2023-09-24 22:57:42.875 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server broadcast: UPDATE_CAMPAIGN_MSG except to 127.0.0.1-0
2023-09-24 22:57:42.877 INFO  net.rptools.maptool.server.ServerMessageHandler - from 127.0.0.1-0 handled: UPDATE_CAMPAIGN_MSG
2023-09-24 22:57:50.973 ERROR net.rptools.clientserver.simple.client.SocketClientConnection - java.net.SocketException: Socket closed
2023-09-24 22:57:50.973 ERROR net.rptools.clientserver.simple.client.SocketClientConnection - java.io.IOException: Stream closed
2023-09-24 22:57:50.974 INFO  net.rptools.maptool.server.MapToolServerConnection - Personal server broadcast: PLAYER_DISCONNECTED_MSG except to 127.0.0.1-0
`

**Comment by Azhrei** [comment]
Can you provide more information, please?  We need the version of the OS (if Linux, which distro and release), the language settings for the OS and for MapTool, whether you have a version of the Java JRE already installed, and anything else we might need to recreate the problem.  (That information is available from the **Help > Gather Debug Info...** menu option, if you can get to that point.)

My initial guess would be that there's a library missing and that's why the `Image.bytesToImage()` function can't convert the file contents into an Image object for display.  If you did what the OP did (extracted files from the .deb without installing it), then any dependencies mentioned in the .deb are being ignored and that's likely a problem.

Google found [this video link (YouTube)](https://www.youtube.com/watch?v=L7KlfJiQ6_s) for how to install a .deb package on Void Linux.  Perhaps you could try that approach?  (And if it works, please report back to let us know.)

**Comment by Ceyyec** [comment]
> Can you provide more information, please? We need the version of the OS (if Linux, which distro and release), the language settings for the OS and for MapTool, whether you have a version of the Java JRE already installed, and anything else we might need to recreate the problem. (That information is available from the **Help > Gather Debug Info...** menu option, if you can get to that point.)
> 
> My initial guess would be that there's a library missing and that's why the `Image.bytesToImage()` function can't convert the file contents into an Image object for display. If you did what the OP did (extracted files from the .deb without installing it), then any dependencies mentioned in the .deb are being ignored and that's likely a problem.
> 
> Google found [this video link (YouTube)](https://www.youtube.com/watch?v=L7KlfJiQ6_s) for how to install a .deb package on Void Linux. Perhaps you could try that approach? (And if it works, please report back to let us know.)

Sorry for the lack of info, I use Arch and have installed the .deb file from the AUR through yay.
Another run from the terminal with DBG=1 told me that the javafx configuration was unsuported.
I'll try installing the .deb from the website and try again and report whether the issue persists or not. Thanks.

**Comment by Ceyyec** [comment]
As I tried to install it with dpkg, it told me that i needed packages which were for debian distrobutions,
I do have the Arch equilavents of those but it still does not let me install, here is the dependency issue error:
`dpkg: dependency problems prevent configuration of maptool:
 maptool depends on libc6; however:
  Package libc6 is not installed.
 maptool depends on xdg-utils; however:
  Package xdg-utils is not installed.
 maptool depends on zlib1g; however:
  Package zlib1g is not installed.
`
