### ISSUE TITLE
.jar file doesn't launch

### ISSUE THREAD

**Issue by agirnob** [RPTools/maptool#2216]
**Describe the bug**
opening the . jar file in manjaro throws a "No toolkit found" pop up and when i tried to open it from terminal it throws the following error:
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:241)
        at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:257)
        at net.rptools.maptool.client.swing.SplashScreen.<init>(SplashScreen.java:37)
        at net.rptools.maptool.client.MapTool.main(MapTool.java:1670)
        at net.rptools.maptool.client.LaunchInstructions.main(LaunchInstructions.java:50)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:832)

and several:  
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.

**To Reproduce**
1. Go to the directory you downloaded the file 
2. Click on .jar file or in the same directory run the following command java -jar "fileName"
3.  "No toolkit found" pop up 

**Expected behavior**
It should open without a problem

**MapTool Info**
- Version: 1.8.0 Beta 2  
- Install: JAR 

**Desktop (please complete the following information):**
 - OS:Linux
 - Version kernel version: 5.7.17-2 MANJARO kde version up-to-date

**Additional context**
i get around issue by downloading the rpm files and putting them in to  corresponding directories

**Comment by Phergus** [comment]
What Java version did you have installed on your system?  MT1.8 requires Java 14 with JavaFX.

When you use the RPM download you are getting the JRE files with it.

**Comment by agirnob** [comment]
i am using adoptopenjdk 14 from aur

**Comment by Phergus** [comment]
Perhaps a graphics issue.

There are two config files:
- User home dir: `.maptool-rptools\config\maptool.cfg`
- Install dir: `app\maptool.cfg`

Try adding these two lines under `[JavaOptions]`
```
-Dsun.java2d.d3d=true
-Dsun.java2d.opengl=true
```

**Comment by Azhrei** [comment]
A Google search on the error message says that the Prism driver requires GTK 2.18; do you have at least that version?

**Comment by agirnob** [comment]
> A Google search on the error message says that the Prism driver requires GTK 2.18; do you have at least that version?

yes i have 2.24 gtk 

>about config: shall i delete maptool? then run the jar file to find those config files of the jar file?

**Comment by bjorn** [comment]
Why was this issue closed? I'm running into the same problem trying to run MapTool 1.11.3 on Ubuntu:
```
bjorn@thor:~/Downloads$ java -jar MapTool-1.11.3.jar 
ERROR StatusLogger Unrecognized format specifier [d]
(... more StatusLogger lines)
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Dec 06, 2021 12:12:01 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5c663359'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:241)
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:257)
	at net.rptools.maptool.client.swing.SplashScreen.<init>(SplashScreen.java:37)
	at net.rptools.maptool.client.MapTool.main(MapTool.java:1697)
	at net.rptools.maptool.client.LaunchInstructions.main(LaunchInstructions.java:51)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I'm using OpenJRE 18:
```
bjorn@thor:~/Downloads$ java -version
openjdk version "18-ea" 2022-03-15
OpenJDK Runtime Environment (build 18-ea+15-Ubuntu-4)
OpenJDK 64-Bit Server VM (build 18-ea+15-Ubuntu-4, mixed mode, sharing)
```
@Phergus I've added this file but it did not help:
```
bjorn@thor:~/Downloads$ cat ~/.maptool-rptools/config/maptool.cfg
[JavaOptions]
-Dsun.java2d.d3d=true
-Dsun.java2d.opengl=true
```

**Comment by Phergus** [comment]
@bjorn it was closed by the person that opened it.  probably because they figured out what they had done wrong.

> [JavaOptions]
-Dsun.java2d.d3d=true
-Dsun.java2d.opengl=true

That's the wrong format for MT 1.9 or later.  It should be:
`java-options=-Dsun.java2d.d3d=false`

MT is built against the OpenJDK 16.0.2  You are on your own for 18.

**Comment by bjorn** [comment]
> MT is built against the OpenJDK 16.0.2 You are on your own for 18.

I was previously using version 11 but then it told me it was too old. I've installed `openjdk-16-jre` now, but the problem persists, also after adjusting to the new format in the cfg file.

Personally I've now switched to the .deb package, which does work. It would be nice if the .jar also worked, but it's not important for me.
