### ISSUE TITLE
Launcher getListOfLanguages NullPointerException

### ISSUE THREAD

**Issue by matejdro** [RPTools/maptool#223]
Not sure what exactly causes this but doing this:

1. Check out https://github.com/RPTools/maptool/tree/be3fa96566c97ab488b9ccea56e685305b582df9
2. Execute `./gradlew run`

prints this exception into console for me:

```
Task :launcher:run

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at net.rptools.maptool.launcher.CopiedFromOtherJars.getListOfLanguages(CopiedFromOtherJars.java:89)
        at net.rptools.maptool.launcher.MapToolLauncher.<init>(MapToolLauncher.java:225)
        at net.rptools.maptool.launcher.MapToolLauncher$21.run(MapToolLauncher.java:1719)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This exception does not appear to cause any issues though (MapTool still launches normally).

This is on Windows 10, 64-bit.

**Comment by Phergus** [comment]
Closing.
