### ISSUE TITLE
Adjusting Grid with Dialog open causes Exception

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#226]
Adjusting the grid of a map with a macro-created Dialog/Frame open produces an exception when the Adjust Grid window is closed.

1.  Start with a completely new campaign file.
2.  Put something on the token layer.
3.  Adjust Grid: everything works.
4.  Execute the following macro: [Dialog("Hello World"): {Hello World}]
5.  Adjust Grid: the error message appears.

```
java.lang.ClassCastException: java.base/java.util.LinkedList cannot be cast to net.rptools.maptool.model.Token
	at net.rptools.maptool.client.ui.htmlframe.HTMLFrameFactory$Listener.modelChanged(HTMLFrameFactory.java:154)
	at net.rptools.maptool.model.BaseModel.fireModelChangeEvent(BaseModel.java:33)
	at net.rptools.maptool.model.Zone.putTokens(Zone.java:1102)
	at net.rptools.maptool.client.tool.GridTool$2.actionPerformed(GridTool.java:123)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:36)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
Verified with 1.4.0.5 & 1.4.1.8.  Windows 10, Java 10

See forum post: http://forums.rptools.net/viewtopic.php?f=86&t=27994

**Comment by Merudo** [comment]
> Note: the same exception occurs even if the dialog has been opened and closed again before invoking adjust grid.

Unless temporary has been set to 1, "closing" the frame/dialog just hides the dialog and doesn't delete it.

**Comment by Merudo** [comment]
My PR #600 fixes the issue.

**Comment by Phergus** [comment]
Tested.  Unable to produce exception.
