### ISSUE TITLE
Exception related to vision after upgrade to 1.8.3

### ISSUE THREAD

**Issue by Piglit** [RPTools/maptool#2411]
**Describe the bug**
I get excpetions (stack-trace below) when hovering over a token (as GM), on selecting a token and when no longer hovering/releasing the token.
The token is a player token with vision.
After removing the vision from the token the exceptions do not longer occure.
Also the bug did not occure on every map (just on some of them), and not with every token.

**To Reproduce**
Can not reproduce on a new map.
After saving and reloading the campaign I only get one exception immediately after changing the vision of the token on the map where the exception usualy occured. The bug completely vanished after moving the tokens around and switching the vision type some times.

**Expected behavior**
Not getting an exception.

**MapTool Info**
- Version: 1.8.3
- Install: Upgrade from 1.7.0
- This occured after loading the campaign directly after upgrading the MapTool version when switching to the map where it occured.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
The stack trace of the exception
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.ComparableTimSort.mergeHi(Unknown Source)
	at java.base/java.util.ComparableTimSort.mergeAt(Unknown Source)
	at java.base/java.util.ComparableTimSort.mergeCollapse(Unknown Source)
	at java.base/java.util.ComparableTimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at java.base/java.util.ArrayList.sort(Unknown Source)
	at java.base/java.util.Collections.sort(Unknown Source)
	at net.rptools.maptool.client.ui.zone.FogUtil.calculateVisibility(FogUtil.java:94)
	at net.rptools.maptool.client.ui.zone.ZoneView.getVisibleArea(ZoneView.java:388)
	at net.rptools.maptool.client.ui.zone.ZoneView.calculateVisibleArea(ZoneView.java:775)
	at net.rptools.maptool.client.ui.zone.ZoneView.getVisibleArea(ZoneView.java:112)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1178)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:885)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Phergus** [comment]
See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8234482

**Comment by Phergus** [comment]
Also see code comments:

https://github.com/RPTools/maptool/blob/536c86a9eb4820653e814863a66c6d342b7783d4/src/main/java/net/rptools/maptool/client/ui/zone/FogUtil.java#L87-L94

**Comment by Phergus** [comment]
@Piglit really need the map that produces this error.

**Comment by MeloDub** [comment]
I think I know what the problem is here, but without a consistent way of reproducing the error it'll be hard do confirm.

Basically, when we call `Collections.sort()` on a list of items that implement the Comparable interface, the `compareTo()` method of the item will be called to do the comparisons to sort the list.
In the compareTo method of VisibleAreaSegment there are some weird calculations done which can cause this exception, the weirdest of all being the (int) cast of line 136.

I believe that casting a long to int without any check is wrong because information is lost during the conversion and worst case scenario, a positive number can become negative (see this example https://stackoverflow.com/a/4355313), thus breaking the contract of the comparison method.

I think the solution to this problem is to just change the compareTo method to simply do `return Long.compare(getDistanceSqFromOrigin(), o.getDistanceSqFromOrigin());` which already does what we need without any type conversion.

Let me know what you think.

**Comment by Phergus** [comment]
Sounds reasonable.

@cwisniew any thoughts?

**Comment by cwisniew** [comment]
This is more than reasonable as it's the recommended way to do comparisons for this exact reason.  (Even intra should use the Integer. compare function not minus)

**Comment by Phergus** [comment]
@MeloDub you want to submit a PR for this?

**Comment by MeloDub** [comment]
Sure, I'll do it.

**Comment by Phergus** [comment]
Tested with some maps with complex VBL and multiple tokens with vision/light without issue but I was never able to reproduce this problem prior to the fix.

**Comment by Phergus** [comment]
Unable to find/create a map/campaign that reproduces issue.  No response from OP.  Considering done.
