### ISSUE TITLE
Set Facing provoke constant java Error

### ISSUE THREAD

**Issue by juan0286** [RPTools/maptool#2416]
**Describe the bug**
When uses Set Facing on a token, provoke java error. This error returns constantly, as long as the pointer is inside the map, forcing you to close MapTool

**To Reproduce**
Using Set Facing from menu option of token or using Shift and mouse-wheel to change facing produces exception below.

Only occurs on Hex Grid Maps saved in previous versions and only until a New/Edit Map Properties dialog has been opened for the aflicted map grid type.

Using Ctrl-Shift with the mouse-wheel does not produce the error.

**Expected behavior**
change Facing, without errors

**Screenshots**

**MapTool Info**
- Version: 1.8.3
- Install: New, Upgrade [1.8.0]

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 
 - Version [18.04 LTS]

**Additional context**
```
java.lang.NullPointerException: Cannot read the array length because "array" is null
	at net.rptools.maptool.util.TokenUtil.getIndexNearestTo(TokenUtil.java:32)
	at net.rptools.maptool.client.tool.FacingTool.mouseMoved(FacingTool.java:105)
	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(Unknown Source)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Piglit** [comment]
I can confirm this and add some information:

* Shift-Mouse-wheel produces a single Exception
* Set facing (via tokens right-click menu) produces a new exception whenever the error window of last one is closed. If you manage to click fast enough, so you click on the map before the next window opens, the exceptions stop. This way you may not need to close the MapTool.
*  When I open the New/Edit Map Properties dialog (and do some dummy changes) the exception no longer occures for me, **but it still occures for connected Players** when they try to change the facing of their tokens.
* The bug also occured on a new created Map (but using tokens created before the 1.8.3 Upgrade)

It only occures on HexMaps.

**Comment by mlangsdorf** [comment]
ctrl-shift-mousewheels allows tokens on a hexmap to be rotated, but only in 1 degree increments.  It is an extremely annoying work-around but hopefully it will help highlight where the actual bug is occuring.

**Comment by Bloodvixen** [comment]
This bug is also confirmed, nearly every time. ~ 1/10 times, the client won't throw an exception.
Have created completely new map with new tokens (1.8.3), will also occur nearly 9/10 times
