### ISSUE TITLE
Exception thrown when opening Preferences menu while running Maptool from code with a translated "Label.startup" string

### ISSUE THREAD

**Issue by MeloDub** [RPTools/maptool#2446]
**Describe the bug**
Maptool throws an exception when trying to open the Preferences menu while running from code and the I18N string "Label.startup" is different from "Startup".

`java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 5
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.desktop/javax.swing.JTabbedPane.setEnabledAt(JTabbedPane.java:1548)
	at net.rptools.maptool.client.ui.PreferencesDialog.setInitialState(PreferencesDialog.java:956)
	at net.rptools.maptool.client.ui.PreferencesDialog.<init>(PreferencesDialog.java:304)
	at net.rptools.maptool.client.AppActions$14.executeAction(AppActions.java:668)
	at net.rptools.maptool.client.AppActions$ClientAction.execute(AppActions.java:3229)
	at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:3261)
        [...]
`

**To Reproduce**
1. In the I18N properties file of the language you are using, change the string associated to the key "Label.startup"
2. Run Maptool from code
3. Open the "Preferences" menu
4. Exception is thrown

**Expected behavior**
Preferences menu opens correctly.

**MapTool Info**
- Version: development version

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by MeloDub** [comment]
I'm working on this.

**Comment by Phergus** [comment]
Tested.  Confirmed exception in original code when run from dev.  Confirmed no exception with fix.
