### ISSUE TITLE
NullPointerException when server shuts down while client connected

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#250]
This link is a report of an NPE:  https://gist.github.com/kayila/d08f255de63435195cd6421a082fc972

The relevant portion is the first few lines:
```
java.lang.NullPointerException
    at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
    at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderTokens(ZoneRenderer.java:3339)
    at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1229)
    at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:790)
    at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
    at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
    ...```

**Comment by Azhrei** [comment]
It appears that the IF statement on line 3338 should also check whether `visibleTokenSet` is null.  I'm assigning this to @JamzTheMan as it has something to do with rendering code from Nerps (apparently).

**Comment by JamzTheMan** [comment]
Are we pushing this to the next release?

**Comment by Azhrei** [comment]
I guess so.  I don't know who the `git blames assigned to that line of code, but you had state you thought there was a reason the class variable hadn't been initialized at the point of declaration.  If you don't want to work on it, then defer it.  I'm fine with that.

**Comment by JamzTheMan** [comment]
Oh wait, this should be fixed. I was thinking this was another issue... Not sure why this is is still open...
