### ISSUE TITLE
Defined Property with empty name produces stacktrace in 1.8.5

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2536]
**Describe the bug**
Reported by Discord user `ster`:
If a campaign includes a property with an empty name (weirdly possible by defining a property with just `*`, as the only way to have a property appear on the stat sheet popup *without* a name), the Edit Macro dialog will fail to open in 1.8.5 with the following stacktrace related to the new Syntax Highlighting for token properties (#2352):

<details>
 <summary>View Stacktrace</summary>

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.fife.ui.rsyntaxtextarea.TokenMap.getHashCode(TokenMap.java:202)
	at org.fife.ui.rsyntaxtextarea.TokenMap.put(TokenMap.java:246)
	at org.fife.ui.rsyntaxtextarea.TokenMap.put(TokenMap.java:227)
	at net.rptools.maptool.client.ui.syntax.MapToolScriptSyntax.<init>(MapToolScriptSyntax.java:124)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory$TokenMakerCreator.create(AbstractTokenMakerFactory.java:128)
	at org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory.getTokenMakerImpl(AbstractTokenMakerFactory.java:55)
	at org.fife.ui.rsyntaxtextarea.TokenMakerFactory.getTokenMaker(TokenMakerFactory.java:79)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.setSyntaxStyle(RSyntaxDocument.java:547)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setSyntaxEditingStyle(RSyntaxTextArea.java:2939)
	at net.rptools.maptool.client.ui.MacroButtonDialog.initCommandTextArea(MacroButtonDialog.java:397)
	at net.rptools.maptool.client.ui.MacroButtonDialog.<init>(MacroButtonDialog.java:129)
	at net.rptools.maptool.client.ui.macrobuttons.buttons.MacroButtonPopupMenu$EditButtonAction.actionPerformed(MacroButtonPopupMenu.java:175)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
</details>

**To Reproduce**
1. For any Token Type included in the campaign, add a new Property defined with just: `*`.
2. Click Update, then OK.
3. Attempt to edit any macro, see error matching the above stacktrace.

**Expected behavior**
One of two options:
1. Properties with empty names should be explicitly allowed, and the editor should work normally by skipping over those properties while building Syntax Highlighting rules.
2. (preferred) Properties with empty names should be explicitly NOT allowed, and it's a non-issue for syntax highlighting.

**MapTool Info**
- Version: 1.8.5

**Additional context**
I'm honestly shocked that a property with an empty name hasn't caused other visible issues elsewhere, and I definitely think we'd be better off not allowing them.  The problem with this is that we don't otherwise have a current method for including a property on the stat sheet popup without displaying its name - empty display names are automatically removed by the property definition dialog.  See #2535

**Comment by Phergus** [comment]
Perhaps add a new Format specifier to indicate that while the property value is shown on the stat sheet the name is not?

My opinion is that empty property names should not be allowed.

**Comment by Azhrei** [comment]
> Perhaps add a new Format specifier to indicate that while the property value is shown on the stat sheet the name is not?

Or just allow the parentheses to be empty to indicate that there's no name to display (since the parens are already part of the format).

> My opinion is that empty property names should not be allowed.

Definitely agree!

**Comment by Phergus** [comment]
> Or just allow the parentheses to be empty to indicate that there's no name to display (since the parens are already part of the format).

That should work well enough.

**Comment by selquest** [comment]
Seems to be the consensus that the best approach is to prevent this situation from occurring entirely, so I'll plan to implement #2535 instead of making syntax highlighting somehow identify a blank line as a defined property :)

To handle campaigns that already have one of these blank properties defined, would we prefer to drop the invalid property on import, or update the definition to include some default name?  `_previouslyUnnamedProperty_`?

**Comment by Azhrei** [comment]
> To handle campaigns that already have one of these blank properties defined, would we prefer to drop the invalid property on import, or update the definition to include some default name? `_previouslyUnnamedProperty_`?

I wouldn't want to remove user data.

I'd say we change the property name to something unique (check to make sure it isn't already there) and add a string the same string to the parens.  That will cause the value to show up on the stat sheet where the author should see it and thus recognize the problem.  When they view the Campaign Properties, they should see it pretty quickly.  But I'm wondering if we should somehow prod them to look at the wiki to see what the issue was and a reminder that they'll need to fix their code...?

**Comment by Phergus** [comment]
I would think that seeing  `_previouslyUnnamedProperty_` show up in the stat sheet should prompt them to ask the question.  I guess the adjusted property names could be  `_previouslyUnnamedProperty1...n_` and then make the short name `_set_to_blank_to_hide_` or something similar.

**Comment by Azhrei** [comment]
> I would think that seeing `_previouslyUnnamedProperty_` show up in the stat sheet should prompt them to ask the question. I guess the adjusted property names could be `_previouslyUnnamedProperty1...n_` and then make the short name `_set_to_blank_to_hide_` or something similar.

I thought about the `1..n` but decided that, _in the end, there can be only one._  Thus, no need for a counter.

And yeah, some long string like that for the display name.  Something that long will be really obvious on the stat sheet since it will throw off any formatting a FW author may have been creating.

**Comment by Phergus** [comment]
> I thought about the 1..n but decided that, in the end, there can be only one. Thus, no need for a counter.

It's good that at least we didn't allow duplicate unnamed properties.
