### ISSUE TITLE
Imported Dungeondraft maps have broken light icons

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2548]
**Describe the bug**
After importing a Dungeondraft Universal VTT map with lights instead of the lightsource icon the red X is appearing.

**To Reproduce**
1. From Map menu select Import Dungeondraft VTT.
2. Select a `.dd2vtt` map file with lights (see attached example)
3. Complete import.
4. Note where the lightbulb icon should be is the dreaded Red X.

**Expected behavior**
Expect the light bulb icon.

**Screenshots**
Bad:
![image](https://user-images.githubusercontent.com/34379254/115122261-35a59980-9f74-11eb-96ab-4cb9740acf30.png)
Good (1.7.0):
![image](https://user-images.githubusercontent.com/34379254/115122288-5b32a300-9f74-11eb-8d8f-1533283797fe.png)

**MapTool Info**
- Version: 1.8.5, 1.9.0-alpha.9
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Reported by Retired Android#1980 on Discord

`lightbulb.png` file is definitely in release and can be verified by adding a light source to any token and then enabling show light sources.

Error from log file:
```
2021-04-17 11:46:29.468 ERROR net.rptools.maptool.util.ImageManager - BackgroundImageLoader.run(LightSource,, d41d8cd98f00b204e9800998ecf8427e): image not resolved
java.io.IOException: Could not load image LightSource
	at net.rptools.lib.image.ImageUtil.bytesToImage(ImageUtil.java:309) ~[MapTool.jar:1.8.5]
	at net.rptools.maptool.util.ImageManager$BackgroundImageLoader.run(ImageManager.java:305) [MapTool.jar:1.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Map file to import: 
[8x8 Small Building with Lights.zip](https://github.com/RPTools/maptool/files/6329757/8x8.Small.Building.with.Lights.zip)

**Comment by Phergus** [comment]
Tested.  Working again.
