### ISSUE TITLE
Popping a warning dialog when pressing any key on macro frame

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#2558]
**Describe the bug**
Popping a warning dialog when pressing any key on macro frame.

**To Reproduce**
1. Create a token, and add a macro button with command ``[frame("test"):{ }]``.
2. Run the macro and emerge a macro frame.
3. Press any key on keyboard when the frame focused.
4. Warning dialog popped (see below).

**MapTool Info**
- Version: 1.9.0-alpha.9
- Install: New
- Language: Japanese

**Desktop:**
 - OS: Windows 10 Pro x64
 - Version 20H2

**Additional context**
Doing same with empty dialog(``[dialog("test"):{ }]``), does not appear warning dialog.

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean javax.swing.JComponent.processKeyBinding(javax.swing.KeyStroke,java.awt.event.KeyEvent,int,boolean) accessible: module java.desktop does not "opens javax.swing" to unnamed module @770d3326
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at com.jidesoft.swing.ResizableDialog$1.processKeyBinding(ResizableDialog.java:138)
	at java.desktop/javax.swing.JComponent.processKeyBindings(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Phergus** [comment]
Confirmed under W10 English locale.

**Comment by Irarara** [comment]
This seems restricted to floating dockable frames. If they're docked it doesn't seem to happen, and as already noted by fw, same goes for dialogs. (I guess because it's an issue in `ResizableDialog` going by the exception?)

**Comment by Phergus** [comment]
This seems to be relevant.
https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m

**Comment by Phergus** [comment]
Note this also happens with the normal MT panels as well as frame()/dialog() panels if they aren't docked.

**Comment by Phergus** [comment]
@kwvanderlinde So the fix mentioned on above was it.  Excellent.

**Comment by Phergus** [comment]
Tested.  Undocked frames (macro and standard) no longer produce exceptions from keyboard input.
