### ISSUE TITLE
Unable to save campaign since move to Java 16

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2587]
**Describe the bug**
When trying to save a campaign, an error dialog is shown and the campaign file is written to.

**To Reproduce**
1. Create a new campaign.
2. Save the campaign.
3. See and close the dialog.
4. Check the save location and observe no campaign file exists.

**Expected behavior**
The campaign file should be written and no error should be generated.

**Screenshots**
This is the dialog that is displayed:
![image](https://user-images.githubusercontent.com/7492219/116324910-d9155c00-a775-11eb-858d-0703b751365e.png)

**MapTool Info**
I am running this in development on the `develop` branch. Bisecting reveals it goes back to 363d8c5e2d521a35f9b4466534385aeeb46bd1c6.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**
Debug information:
```
==== MapTool Information ====
MapTool Version: DEVELOPMENT
MapTool Home...: /home/kenneth/.maptool
MapTool Install: /home/kenneth/Documents/Coding/Open Source/maptool/build/classes/java
Max mem avail..: 3 GB
Max mem used...: 144 MB

==== Java Information ====
Java Home......: /home/kenneth/.jdks/openjdk-16.0.1
Java Vendor....: Oracle Corporation
Java Version...: 16.0.1
Java Parameters: 
  -Dfile.encoding=UTF-8
  -Duser.country=CA
  -Duser.language=en
  -Duser.variant


==== OS Information ====
OS Name........: Linux
OS Version.....: 5.4.0-72-generic
OS Architecture: amd64
PATH...........: /home/kenneth/.local/bin:/home/kenneth/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Number of Procs: 6

==== User Information ====
User Name: kenneth
User Home: /home/kenneth
User Dir.: /home/kenneth/Documents/Coding/Open Source/maptool

==== Network Interfaces ====
Display Name..: zthnhauxdb
Interface Name: zthnhauxdb
Address...: fe80:0:0:0:9cb4:eff:fe99:671d%zthnhauxdb
Address...: 172.29.224.214

Display Name..: zt44xpuk3a
Interface Name: zt44xpuk3a
Address...: fe80:0:0:0:1808:a0ff:fe76:656%zt44xpuk3a
Address...: 172.25.224.214

Display Name..: wlp4s0
Interface Name: wlp4s0
Address...: fe80:0:0:0:3eb9:61df:732c:48e9%wlp4s0
Address...: 192.168.0.111

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: Canada
Language: English
Locale..: English (Canada)
Variant.: 

==== Encoding Information ====
Default Locale:   en_CA
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1920x1080(-1)
Display 2: 1920x1080(-1)

==== Internet Gateway Devices ====
Device Name.: Wireless Broadband Router
Model Name..: D-Link Router
Manufacturer: D-Link Corporation
Model Number: DIR-859
Model Desc..: D-Link Router
Firmware....: Linux, UPnP/1.0, DIR-859 Ver 1.07
External IP.: 192.168.1.68
```

Log console:
```
16:31:32.222 ERROR net.rptools.maptool.client.MapTool - msg.error.failedSaveCampaign
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.awt.geom.Area
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static java.util.Vector java.awt.geom.Area.EmptyCurves accessible: module java.desktop does not "opens java.awt.geom" to unnamed module @5fb2de77
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:483) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:48) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:79) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1276) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1265) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1238) ~[xstream-1.4.16.jar:1.4.16]
	at net.rptools.lib.io.PackedFile.putFile(PackedFile.java:486) ~[main/:?]
	at net.rptools.lib.io.PackedFile.setContent(PackedFile.java:414) ~[main/:?]
	at net.rptools.maptool.util.PersistenceUtil.saveCampaign(PersistenceUtil.java:302) ~[main/:?]
	at net.rptools.maptool.client.AppActions$CampaignSaver.doInBackground(AppActions.java:2590) ~[main/:?]
	at org.jdesktop.swingworker.SwingWorker$1.call(Unknown Source) ~[swing-worker-1.2.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at org.jdesktop.swingworker.SwingWorker.run(Unknown Source) ~[swing-worker-1.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
16:31:39.305 INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 5
16:31:39.307 INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
16:31:39.343 ERROR net.rptools.maptool.client.MapTool - AutoSaveManager.failed
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$SynchronizedMap
converter           : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[1]          : Unable to make private void java.util.Collections$SynchronizedMap.writeObject(java.io.ObjectOutputStream) throws java.io.IOException accessible: module java.base does not "opens java.util" to unnamed module @5fb2de77
converter[1]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[2]          : Unable to make field private static final long java.util.Collections$SynchronizedMap.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @5fb2de77
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:483) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:48) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1276) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1265) ~[xstream-1.4.16.jar:1.4.16]
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1238) ~[xstream-1.4.16.jar:1.4.16]
	at net.rptools.lib.io.PackedFile.putFile(PackedFile.java:486) ~[main/:?]
	at net.rptools.lib.io.PackedFile.setContent(PackedFile.java:414) ~[main/:?]
	at net.rptools.maptool.util.PersistenceUtil.saveCampaign(PersistenceUtil.java:302) ~[main/:?]
	at net.rptools.maptool.client.AutoSaveManager$SaveWorker.doInBackground(AutoSaveManager.java:128) ~[main/:?]
	at net.rptools.maptool.client.AutoSaveManager$SaveWorker.doInBackground(AutoSaveManager.java:112) ~[main/:?]
	at javax.swing.SwingWorker$1.call(SwingWorker.java:304) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at javax.swing.SwingWorker.run(SwingWorker.java:343) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by kwvanderlinde** [comment]
Similar converter-based errors also show when trying to add tokens, either by dragging an image/token from the Library from the file explorer.

**Comment by Phergus** [comment]
@thelsing reported the same issue on Discord  https://discord.com/channels/296230822262865920/494598206626463755/835215266614607902

But got it sorted out later.  Maybe have been the IntelliJ run config was using the wrong Java version.

**Comment by kwvanderlinde** [comment]
Thanks for the link, I'll look into that.

**Comment by kwvanderlinde** [comment]
This was indeed just a matter of using an incorrect run configuration. A typical run via `JAVA_HOME=...  ./gradlew run` works fine, as does using IntelliJ's built-in gradle support.
