### ISSUE TITLE
Exception while trying to add a local folder as a resource to library

### ISSUE THREAD

**Issue by MeloDub** [RPTools/maptool#2742]
**Describe the bug**
An exception occurs while trying to add a local folder as a resource to the assets library. This is confirmed to happen on Windows installation, but not on MacOS (tried by @Azhrei). 

Stack-trace:
```
java.lang.IllegalAccessError: class com.jidesoft.plaf.basic.BasicFolderChooserUI (in unnamed module @0x53fdffa1) cannot access class sun.awt.shell.ShellFolder (in module java.desktop) because module java.desktop does not export sun.awt.shell to unnamed module @0x53fdffa1
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.isFileSystem(BasicFolderChooserUI.java:545)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.getTreePathForFile(BasicFolderChooserUI.java:569)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.ensureFileIsVisible(BasicFolderChooserUI.java:596)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.access$100(BasicFolderChooserUI.java:35)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI$FolderChooserPropertyChangeListener.propertyChange(BasicFolderChooserUI.java:627)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.<init>(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.<init>(Unknown Source)
	at com.jidesoft.swing.FolderChooser.<init>(FolderChooser.java:63)
	at net.rptools.maptool.client.ui.AddResourceDialog.lambda$initLocalDirectoryButton$1(AddResourceDialog.java:150)
        [...]
```

**To Reproduce**
1. Go to 'File'
2. Click on 'Add resource to library'
3. On 'Local folder' click on the '...' button
4. Exception occurs

**Expected behavior**
The file system explorer window should open to let you select the folder you want to add as resource.

**MapTool Info**
- Version: 1.9.0
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This issue is solved by adding the following java option to the [Java Options] section in MapTool.cfg:
`java-options=--add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED`

**Comment by Phergus** [comment]
As a workaround you can paste the desired path into the field and click on Install.
![image](https://user-images.githubusercontent.com/34379254/122439678-18cc1900-cf59-11eb-97a3-f1f09a30c00a.png)

**Comment by Phergus** [comment]
Tested.  No longer causes an exception when browsing for directory.
