### ISSUE TITLE
Corrupted initiative list prevents campaign to be served to clients

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#2776]
**Describe the bug**
A campaign sets into a 
In some cases, initiative list on a map can become corrupted and prevent the campaign from being served to clients.

In those cases, on the server the following trace-back is shown:

```
java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.model.InitiativeList$TokenInitiative.isHolding()" because "oldti" is null
	at net.rptools.maptool.model.Zone.<init>(Zone.java:454)
	at net.rptools.maptool.model.Campaign.<init>(Campaign.java:172)
	at net.rptools.maptool.client.AutoSaveManager.executeAndContinue(AutoSaveManager.java:102)
	at net.rptools.maptool.client.AutoSaveManager.execute(AutoSaveManager.java:63)
	at net.rptools.maptool.client.AutoSaveManager.lambda$start$0(AutoSaveManager.java:49)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**To Reproduce**
I couldn't find yet the behavior which causes the initiative list to become corrupted. Once there is a corrupted initiative, the following causes the issue:

1. start MapTool
2. load the corrupted campaign
3. start a server
4. try to connect with a client
5. the client connects, but doesn't see any map 
6. also, the traceback above shows on the server

**Expected behavior**
The client should see the list of maps, and no traceback should be shown on the server.

**Screenshots**

**MapTool Info**
- 1.9.2, but I am quite sure I have seen this also on 1.8.x

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
As per the traceback, the problem seems to appear in line 454 of Zone.java file. This is the code around there:

```
    // Set the initiative list using the newly create tokens.
    if (saveInitiative.length > 0) {
      for (int i = 0; i < saveInitiative.length; i++) {
        Token token = (Token) saveInitiative[i][0];
        initiativeList.insertToken(i, token);
        TokenInitiative ti = initiativeList.getTokenInitiative(i);
        TokenInitiative oldti = (TokenInitiative) saveInitiative[i][1];
        ti.setHolding(oldti.isHolding());
        ti.setState(oldti.getState());
      }
    }
```

Apparently it is possible that oldti is returned as null, and this causes the problem. Adding a guard on the value of oldti fixes the problem (the campaign is properly downloaded by the clients, and no traceback appears on the server); however, it is unclear why this should become corrupted in the first place.

**Comment by Phergus** [comment]
Concurrency issue?
