### ISSUE TITLE
Grid aura on gridless map renders whole map unusable

### ISSUE THREAD

**Issue by kmuir10** [RPTools/maptool#2955]
**Description**
Activating a grid aura on a token within a gridless map causes an endless series of rapid null pointer exceptions which greatly interfere with normal usage of the program. 

**Steps To Reproduce**
1. Start MapTool
2. Map->Edit Map -> Cell Type -> select No Grid (red x)
3. Edit->Campaign Properties->Light
4. Add the following lines to the text body 
`Sample Auras - 5" square grid ---- ` `Aura red 10: aura grid GM 7.5#ff0000`
5. Drag a token onto the map. Right click it -> Light Sources -> Sample Auras... -> Aura red 10
6. See errors

**Expected behavior**
Have the aura default to being a circle or a square if there is no grid, or simply display nothing, perhaps along with notice that grid auras won't work on gridless maps.

**MapTool Info**
- Version: 1.9.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Switching to a different map stops the flood of exceptions, after which the aura can be deleted from the campaign properties to render the map usable again.

**Comment by dorpond** [comment]
I confirmed that this even happens in MT 1.8.4

You can use this for testing. Just replace the default **campaign properties -> lighting** with this:
```
D20
----
Works: aura GM circle 7.5#ff0000
Fails: aura grid GM 7.5#ff0000
```

The grid option throws it.

Error output:
```
java.lang.NullPointerException: Cannot invoke "java.awt.Shape.getPathIterator(java.awt.geom.AffineTransform)" because "<parameter1>" is null
	at java.desktop/java.awt.geom.Area.<init>(Unknown Source)
	at net.rptools.maptool.model.Grid.createGridArea(Grid.java:831)
	at net.rptools.maptool.model.Grid.getGridAreaFromCache(Grid.java:915)
	at net.rptools.maptool.model.Grid.getGridArea(Grid.java:759)
	at net.rptools.maptool.model.Grid.getShapedArea(Grid.java:389)
	at net.rptools.maptool.model.Light.getArea(Light.java:110)
	at net.rptools.maptool.model.LightSource.getArea(LightSource.java:156)
	at net.rptools.maptool.client.ui.zone.ZoneView.getLights(ZoneView.java:583)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderAuras(ZoneRenderer.java:1603)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1264)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:885)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by dorpond** [comment]
Another observation:

This will Fail:
- Start MT
- Replace Campaign Properties -> Lighting with those that I supplied above.
- Make a new map and make it gridless.
- drop a token on the map and select the "fails" lighting option.

This will work:
- Start MT
- Replace Campaign Properties -> Lighting with those that I supplied above.
- Make a new map, but make it square grid.
- Drop a token on the map, and select 'fails' lighting option.
- Verify aura works fine.
- Edit the existing map and change it to gridless.
- Verify the aura on existing token works fine.
- Verify that all tokens, old and new work fine when selecting the 'fails' light option.

So here is a temporary workaround until this is fixed:
(Assuming your lighting was already preset)

- Create all your maps with the square grid setting.
- Change the map to gridless, and it will work fine.

(Note, all this was tested in 1.8.4)

**Comment by Phergus** [comment]
Tested.  Grid auras on gridless maps no longer cause exception.
