### ISSUE TITLE
Error on importing dd2vtt file

### ISSUE THREAD

**Issue by bigbjor** [RPTools/maptool#3061]
**Software/OS:**
MapTool v 1.10.2 (Linux deb package - freshly installed this morning with no previous versions installed in /opt)

**Steps to reproduce:**
Map -> Import Dungeondraft VTT (selected file TestMap1.dd2vtt)

**Extra information:**
dd2vtt created in Dungeon Alchemist (just entered beta after Kickstarter) so issue may well be in the map and not in MapTool. I'm trying to report to both teams. Zipped map file attached at end of report.

<details>
<summary>
Details of error are:<br>
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null<br>
at net.rptools.maptool.client.utilities.DungeonDraftImporter.importVTT(DungeonDraftImporter.java:118)

</summary>
at net.rptools.maptool.client.AppActions$72.executeAction(AppActions.java:2943)
at net.rptools.maptool.client.AppActions$ClientAction.execute(AppActions.java:3396)
at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:3428)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
at de.muntjak.tinylookandfeel.TinyMenuItemUI.doClick(Unknown Source)
at de.muntjak.tinylookandfeel.TinyMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
</details>

[TestMap1.zip](https://github.com/RPTools/maptool/files/7357649/TestMap1.zip)

**Comment by Phergus** [comment]
DD2VTT format not followed correctly.

Has a `version` element instead of `format`.
```JSON
{
  "version": "0.2",
  "resolution": {
    "map_origin": {
      "x": 0,
      "y": 0
    },
  ...
}
```
Should be:
```JSON
{
  "format":  0.2,
  "resolution": {
    "map_origin": {
      "x": 0,
      "y": 0
    },
  ...
}
```
With correction file loads correctly with VBL in place.

**Comment by cwisniew** [comment]
@Phergus  You just beat me to it :)
I think we should leave this issue open for now as the importer really could provide better information if it fails.
