### ISSUE TITLE
[Bug]: FileNotFoundException due to filename upper/lowercase mismatch

### ISSUE THREAD

**Issue by BlackPhoenix** [RPTools/maptool#3146]
### Describe the Bug

Starting Maptool from the command-line, I notice the console error below when I try to edit a macro. It does not appear to cause an issue - Maptool functions perfectly fine, and I can edit my macro without any issue. It's a minor issue, but a bug nonetheless.

The file specified is indeed missing, but there is another one present: "Default.xml" in the same folder. But since Linux is case-sensitive, it fails to find the specified file.
<details>
<summary>

```
java.io.FileNotFoundException: /home/black/.maptool-rptools/themes/syntax/default.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at net.rptools.maptool.client.ui.MacroButtonDialog.initCommandTextArea(MacroButtonDialog.java:421)
	at net.rptools.maptool.client.ui.MacroButtonDialog.<init>(MacroButtonDialog.java:129)
	at net.rptools.maptool.client.ui.macrobuttons.buttons.MacroButtonPopupMenu$EditButtonAction.actionPerformed(MacroButtonPopupMenu.java:175)
```
</summary>

```
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```
</details>
### To Reproduce

1. Open Maptool in Linux using the command line;
2. Create / edit a macro. The error appears in the console.

### Expected Behaviour

Consistent file naming convention.

### MapTool Info

v1.10.4, new install.

### Desktop

Linux (Gentoo)

**Comment by Phergus** [comment]
Needs testing by someone on Linux.

**Comment by Phergus** [comment]
@BlackPhoenix can you test this with 1.12.0 Alpha 1?

**Comment by BlackPhoenix** [comment]
@Phergus I confirm that the exception does not appear under 1.12.0 Alpha 1.

Thank you!
