### ISSUE TITLE
[Bug]: Java Error when players connect to Campaign Server

### ISSUE THREAD

**Issue by TDenigMa** [RPTools/maptool#3193]
### Describe the Bug

Maptool Version 1.10.3

After hosting a server on MapTool, players successfully connect to it but are then spammed by the following error:

java.lang.NullPointerException: Cannot invoke "net.rptools.parser.function.Function.evaluate(net.rptools.parser.Parser, net.rptools.parser.VariableResolver, String, java.util.List)" because "function" is null
    at net.rptools.maptool.client.functions.ExecFunction.runExecFunction(ExecFunction.java:206)
    at net.rptools.maptool.client.functions.ExecFunction.receiveExecFunction(ExecFunction.java:143)
    at net.rptools.maptool.client.ClientMethodHandler.lambda$handleMethod$0(ClientMethodHandler.java:397)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

I think its important to mention that the Campaign file is based on Takehara's 5E framework and had the following drop in tools installed:
-TheDoor by Wolph42
-Takehara's 5E Tools and D&DBeyond importers

When MapTool updated to version 1.10.3 we successfully played in it with the same conditions described earlier without any error messages. Only a week later did this error show up.

Players receive the same error message when connecting to a Autosave file of the same campaign file. After trying a backup file I had without TheDoor tool, the problem disappeared.

As the DM, I never saw any of the errors, even when they received it.

### To Reproduce

Connect as a Player to a Server with a Campaign using Takehara's 5E Framework with TheDoor and D&DBeyond and 5E Importer Tools on version 1.10.3
Error message shows up a few seconds after successfully connecting.

### Expected Behaviour

Players should be able to interact with MapTool

### MapTool Info

1.10.3

### Desktop

Windows 10

### Additional Context

java.lang.NullPointerException: Cannot invoke "net.rptools.parser.function.Function.evaluate(net.rptools.parser.Parser, net.rptools.parser.VariableResolver, String, java.util.List)" because "function" is null
    at net.rptools.maptool.client.functions.ExecFunction.runExecFunction(ExecFunction.java:206)
    at net.rptools.maptool.client.functions.ExecFunction.receiveExecFunction(ExecFunction.java:143)
    at net.rptools.maptool.client.ClientMethodHandler.lambda$handleMethod$0(ClientMethodHandler.java:397)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by VagruariesOfFate** [comment]
The addons have been installed for some time and were not updated or changed before the error appeared.

Confirmed with user that nothing other than play data was changed before break.

A backup file was loaded and successfully connected to so there is no problem with the MT installation itself.

**Comment by cwisniew** [comment]
It appears that one of the Lib:tokens that are installed is trying to remotely execute a function that is not defined/doesn't exist. If it's continuing to happen then the lib:token is probably calling it over and over. 

Is there any chance of narrowing it down so we can rule out lib:token macro bug (which it seems to be). Stopping MT from displaying the error is probably not desirable as then something will be going wrong but no one will be informed of that.
