### ISSUE TITLE
[Bug]: Illegal Access Error on launch (Windows)

### ISSUE THREAD

**Issue by darovic** [RPTools/maptool#3227]
### Describe the Bug

A warning window opens reporting an Illegal Access Error when launching Map Tool. Strangely, this doesn't stop the program from working. This also occured in v1.10.3.
```
java.lang.IllegalAccessError: class net.rptools.maptool.server.proto.HandshakeMsg tried to access private field com.google.protobuf.AbstractMessage.memoizedSize (net.rptools.maptool.server.proto.HandshakeMsg and com.google.protobuf.AbstractMessage are in unnamed module of loader 'app')
	at net.rptools.maptool.server.proto.HandshakeMsg.getSerializedSize(HandshakeMsg.java:690)
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:62)
	at net.rptools.maptool.server.ClientHandshake.sendMessage(ClientHandshake.java:146)
	at net.rptools.maptool.server.ClientHandshake.startHandshake(ClientHandshake.java:139)
	at net.rptools.maptool.client.MapToolConnection.start(MapToolConnection.java:76)
	at net.rptools.maptool.client.MapTool.createConnection(MapTool.java:1227)
	at net.rptools.maptool.client.MapTool.startPersonalServer(MapTool.java:1194)
	at net.rptools.maptool.client.MapTool.initialize(MapTool.java:695)
	at net.rptools.maptool.client.MapTool.lambda$main$10(MapTool.java:1789)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

### To Reproduce

1. Launch Map Tool

### Expected Behaviour

No error message.

### Screenshots

![image](https://user-images.githubusercontent.com/2281064/144159343-b6bd8eb0-be58-44a6-ba45-9b733244aad9.png)

### MapTool Info

Version: 1.11.0   Install Type: New

### Desktop

Windows 11 Pro Version 21H2 Build 22000.318

### Additional Context

```
==== MapTool Information ====
MapTool Version: 1.11.0
MapTool Home...: C:\Users\[USERNAME_REDACTED]\.maptool-rptools
MapTool Install: C:\Users\[USERNAME_REDACTED]\AppData\Local\MapTool\app
Max mem avail..: 7 GB
Max mem used...: 164 MB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\[USERNAME_REDACTED]\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: C:\Users\[USERNAME_REDACTED]\AppData\Local\MapTool\runtime
Java Vendor....: Eclipse Foundation
Java Version...: 16.0.2
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  -Djpackage.app-path=C:\Users\[USERNAME_REDACTED]\AppData\Local\MapTool\MapTool.exe


==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
PATH...........: C:\Users\[USERNAME_REDACTED]\AppData\Local\MapTool;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\WireGuard\;C:\Users\[USERNAME_REDACTED]\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PowerShell\7\;C:\Users\[USERNAME_REDACTED]\AppData\Local\Microsoft\WindowsApps;C:\Users\[USERNAME_REDACTED]\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\[USERNAME_REDACTED]\Utilities\ffmpeg-20191126-59d264b-win64-static\bin;C:\Users\[USERNAME_REDACTED]\AppData\Local\Yarn\bin;C:\Users\[USERNAME_REDACTED]\.dotnet\tools;C:\Users\[USERNAME_REDACTED]\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\[USERNAME_REDACTED]\AppData\Local\Keybase\;C:\Program Files\Multipass\bin;C:\Users\[USERNAME_REDACTED]\Utilities\bin;C:\Users\[USERNAME_REDACTED]\spicetify-cli;C:\Users\[USERNAME_REDACTED]\Utilities\openssl-3.0.0-win64-mingw\bin;C:\Users\[USERNAME_REDACTED]\.dotnet\tools;C:\Program Files (x86)\Nmap;.
Number of Procs: 24

==== User Information ====
User Name: [USERNAME_REDACTED]
User Home: C:\Users\[USERNAME_REDACTED]
User Dir.: C:\Users\[USERNAME_REDACTED]\AppData\Local\MapTool

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Intel(R) I211 Gigabit Network Connection
Interface Name: eth0
Address...: 192.168.1.2

Display Name..: WireGuard Tunnel
Interface Name: net7
Address...: 10.253.4.39

Display Name..: Hyper-V Virtual Ethernet Adapter
Interface Name: eth23
Address...: 172.21.32.1
Address...: fe80:0:0:0:8c96:d3f4:f527:64b3%eth23

Display Name..: Hyper-V Virtual Ethernet Adapter #2
Interface Name: eth28
Address...: 172.28.32.1
Address...: fe80:0:0:0:2c1c:85cb:aeae:2c75%eth28

Host Address...: 10.253.4.39
Default Gateway: 192.168.1.13

==== Locale Information ====
Country.: Australia
Language: English
Locale..: English (Australia)
Variant.: 

==== Encoding Information ====
Default Locale:   en_AU
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 5120x1440(32)

==== Internet Gateway Devices ====
	No IGDs Found!

```

**Comment by Paul2198** [comment]
I got the same Issue. I fixed it by uninstall MapTool and then reinstall it.

**Comment by Phergus** [comment]
This is typically caused by install a new version on top of an older one.  As he said, uninstall and then reinstall.

**Comment by darovic** [comment]
That did it, thank you. :)
