### ISSUE TITLE
[Bug]: createToken() produce a incomplete token

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#3308]
### Describe the Bug

A token created by ``createToken()`` function is not recognized for outside of the creator.

### To Reproduce

1. Launch MapTool and start server.
2. Launch MapTool other PC, and connect to that server.
3. In the server side, drop a "Dragon" token from MapTool resouce on the map (only use to refer asset ID).
4. Run the macro on the server: ``[createToken(json.set("{}", "name","test", "tokenImage", getImage("Dragon")))]``
5. A new token is appeared on the GM's map, but is not on the player's map.
6. on the GM's map,  the token is able to found by ``findToken()`` function. But on the palyer's map, is not (via trusted macro).
7. Dragging the new token on the GM's map, player's MapTool show a dialog with "An unexpected error has occurred.", and the new token is appeared on the player's map. Now in player's map, the token is able to found by ``findToken()``.

"An unexpected error has occurred." dialog contains below.
~~~
java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.model.Token.isSnapToGrid()" because "this.token" is null
	at net.rptools.maptool.client.ui.zone.ZoneRenderer$SelectionSet.<init>(ZoneRenderer.java:4286)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.addMoveSelectionSet(ZoneRenderer.java:359)
	at net.rptools.maptool.client.ClientMethodHandler.lambda$handleMethod$2(ClientMethodHandler.java:562)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
~~~

**campaign file used for test**
[createToken-problem.cmpgn.zip](https://github.com/RPTools/maptool/files/7798532/createToken-problem.cmpgn.zip)

### Expected Behaviour

Created tokens are able to recognized always.

### MapTool Info

Version: 1.11.4

### Desktop

Windows 10

### Additional Context

A token created using ``createToken()`` in player's MapTool is not recognized in GM's MapTool.

**Comment by Phergus** [comment]
Appears to have been fixed by changes made for 1.12.
