### ISSUE TITLE
[Bug]: Panning (Horizontal Scroll) produces NPE with token selected.

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3315]
### Describe the Bug

In a clean campaign a selected token changes facing when panning left/right with the mouse.
In the attached campaign, with a token selected, panning left or right produces a NPE.

### To Reproduce

1. In that attached campaign. Select a Hero token.
2. Pan left or right

### Expected Behaviour

I expected nothing to start with. When testing this I discovered the rotation feature so now I expect that.

### Screenshots

```
java.lang.NullPointerException: Cannot read the array length because "array" is null
	at net.rptools.maptool.util.TokenUtil.getIndexNearestTo(TokenUtil.java:32)
	at net.rptools.maptool.client.tool.DefaultTool.mouseWheelMoved(DefaultTool.java:324)
	at java.desktop/java.awt.Component.processMouseWheelEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

### MapTool Info

v1.11.4

### Desktop

Win10

### Additional Context

I originally thought this was overlay related (overlay catches mouse events), or some weird setting in an onCampaignLoad macro.
Disabling the onCampaignLoad macros did not make the problem go away and it happens without the overlay open on a fresh start.

Is a mystery

[Events_Skinny.cmpgn.zip](https://github.com/RPTools/maptool/files/7811830/Events_Skinny.cmpgn.zip)

**Comment by Phergus** [comment]
Can't reproduce as described.  When you say "pan" you are talking about holding down RMB and dragging left or right, yes?

As the error is coming from the mouse-wheel handler and you mention rotation I suspect there is more to this.

**Comment by bubblobill** [comment]
> Can't reproduce as described. When you say "pan" you are talking about holding down RMB and dragging left or right, yes?

No. As in mousewheel left and mousewheel right.

**Comment by FullBleed** [comment]
Not all mice have a horizontal scroll wheel (which, apparently, changes facing when used in MT.)

I'm not on 1.11.4, but I did test on 1.10.4 and there was no error.

**Comment by Phergus** [comment]
> No. As in mousewheel left and mousewheel right. **I use a trackpad.** So in the same way I scroll up down with two fingers to emulate mousewheel, I scroll left right with two fingers side to side.

That's a pretty important little factoid.

**Comment by kwvanderlinde** [comment]
This issue isn't really caused by panning per se. It's just that horizontal panning is the same as holding shift and scrolling - which is how a token's facing can be changed.

The actual conditions to reproduce are something like this:
1. **New Map Grid Type** preference is something other than square.
2. Have to load an existing campaign with a square grid map (skipping the `SquareGrid` constructors).
3. On a square grid, change the facing of a token either:
    - by holding shift and scrolling; or
    - by right-click and using the "Set Facing" tool.

The bug seems specific to the square grid not initializing static state properly. It's not an issue since introducing protobuf, since we re-instantiate the grid objects as a side effect of that change, and that causes the static state to be inited.

I'll make a PR to fix the underlying weakness in the code since it's still there. But this bug is probably not reproducible for some time now.
