### ISSUE TITLE
[Bug]: Some VBL triggers error regarding orientation

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3561]
### Describe the Bug

When enabling vision with certain VBL present, an error dialog is repeated shown with the message: "Ring has fewer than 4 points, so orientation cannot be determined".

### To Reproduce

1. Unzip and open this campaign file: [vbl-not-enough-points.cmpgn.zip](https://github.com/RPTools/maptool/files/9417557/vbl-not-enough-points.cmpgn.zip)
2. Edit the Elf token and give it normal vision.
3. Observe the error dialog being shown.
 

### Expected Behaviour

The VBL in the attached map can be handled as-is without showing an error dialog.

### Screenshots

This is the offending VBL:
![offending-vbl](https://user-images.githubusercontent.com/7492219/186463621-761e79f0-a46f-4b9b-a344-ccd4e112136f.png)

Zooming in doesn't show any obvious oddities.

### MapTool Info

1.12.0 beta 1

### Desktop

Linut Mint 21

### Additional Context

This is the full message in the error dialog:
<details>
<summary>
java.lang.IllegalArgumentException: Ring has fewer than 4 points, so orientation cannot be determined
</summary>
<pre>
	at org.locationtech.jts.algorithm.Orientation.isCCW(Orientation.java:128)
	at net.rptools.maptool.client.ui.zone.vbl.AreaMeta.close(AreaMeta.java:140)
	at net.rptools.maptool.client.ui.zone.vbl.AreaTree.digest(AreaTree.java:74)
	at net.rptools.maptool.client.ui.zone.vbl.AreaTree.<init>(AreaTree.java:40)
	at net.rptools.maptool.client.ui.zone.ZoneView.getTopologyTree(ZoneView.java:143)
	at net.rptools.maptool.client.ui.zone.ZoneView.getVisibleArea(ZoneView.java:368)
	at net.rptools.maptool.client.ui.zone.ZoneView.calculateVisibleArea(ZoneView.java:684)
	at net.rptools.maptool.client.ui.zone.ZoneView.getVisibleArea(ZoneView.java:80)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1142)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:846)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre>
</details>

**Comment by kwvanderlinde** [comment]
> Somehow the VBL in question is an idealized line.

Actually I'm way out on this one. Somehow the VBL `Area` in this campaign has a `SEG_CUBICTO` segment. I didn't realize that was possible with our VBL implementation :grimacing:
