### ISSUE TITLE
[Bug]: Load campaign, start server, and token imported from Hero Lab loses binding

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3591]
### Describe the Bug

My "Melee Attack" macro for the "Galirex Hellbane" token works until you start the server at which point the token appears to lose a binding that causing the Hero Lab part of the API to break (the Hero Lab MapTool macros).

See reproduction steps.

### To Reproduce

1. Start MapTool 1.12.0 Beta 2.
2. Load the "test.cmpgn":

[test.zip](https://github.com/RPTools/maptool/files/9485994/test.zip)

3. Go to the Campaign window.
4. Select the "Galirex Hellbane" token on the "Grasslands" map.
5. Click "Melee Attack".
6. Choose "No" (so that as GM you do not do this in secret).
7. Choose "bite (kitsune) (melee)".
8. Click "Okay".
9. Leave the default "No" selected for "Is this a coup de grace?".
10. Click "Okay & Include Temporary Changes" (yes, there's multiple buttons like this and it doesn't matter which one you click.
11. Notice in the Chat window that it worked.
12. Now, start the server with the options illustrated in the attachment:

![Screenshot 2022-09-04 203428](https://user-images.githubusercontent.com/50708405/188343483-8a2b5409-adea-4f20-9aba-6423d2ce8e9c.JPG)

13. Repeat steps 2 through 4 and notice that now you get the following error:

java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "net.rptools.maptool.model.HeroLabData.getPortfolioFile()" is null error executing expression heroLabInfo = herolab.getInfo().
Error trace : TokenHeroLabSync@Lib:CharacterSheet <<< TokenUpdateToLatestMacroVersion@Lib:CharacterSheet <<< Melee Attack@campaign

### Expected Behaviour

Clicking the "Melee Attack" macro with the "Galirex Hellbane" token selected should still work.  You should not get an error.

### MapTool Info

MapTool 1.12.0 Beta 2

### Desktop

Windows 10

### Additional Context

This issue might be related to an issue reported in #3280.

**Comment by adventuremagic123** [comment]
test.cmpgn is inside test.zip.  Unzip test.zip.

**Comment by adventuremagic123** [comment]
Just like in #3280, if you **start the server** BEFORE loading "test.cmpgn" everything works as expected -- there is no error.

However, if you encounter the problem as described by this bug and you save "test.cmpgn", the issue will be persisted to "test.cmpgn", so if you load it again with a freshly started MapTool application you will continue to see the issue whether or not the server is started.

**Comment by adventuremagic123** [comment]
If you do the "To reproduce" steps AND in step 5 double click on the token to open the "Edit Token" dialog, you get a stack trace:

java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.model.Token.getOwners()" because the return value of "net.rptools.maptool.client.ui.token.EditTokenDialog.getModel()" is null
	at net.rptools.maptool.client.ui.token.EditTokenDialog$OwnerListModel.<init>(EditTokenDialog.java:2171)
	at net.rptools.maptool.client.ui.token.EditTokenDialog.lambda$bind$0(EditTokenDialog.java:299)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.displayPopup(MapToolEventQueue.java:109)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:73)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by adventuremagic123** [comment]
I'll stress that the current work-around is to start the server BEFORE loading campaign files and everything is okay.

**Comment by adventuremagic123** [comment]
"test.cmpgn" is virgin MapTool 1.12.0 Beta 2.  In other words, while all the macros and the campaign properties were created in MapTool 1.11.5 (and have a lineage all the way back to MapTool 1.4.x), "test.cmpgn" was created directly in MapTool 1.12.0 Beta 2.

**Comment by adventuremagic123** [comment]
You should **not need the Hero Lab file NOR Hero Lab**, but I've attached the Hero Lab file.  Unzip "Galirex_Hellbane.zip", which contains "Galirex_Hellbane.por".  You might have trouble using it in your Hero Lab because it requires a beefy license (but again, you should NOT need Hero Lab for this issue).

[Galirex_Hellbane.zip](https://github.com/RPTools/maptool/files/9486181/Galirex_Hellbane.zip)

**Comment by cwisniew** [comment]
I can reproduce this in the beta build, but not with the current code in the dev branch, so hopefully, this is already fixed.

**Comment by adventuremagic123** [comment]
Thank you.  Will retest in next beta release.

**Comment by adventuremagic123** [comment]
I'm able to reproduce this issue with MapTool 1.12.0 Beta 3.

I think the problem is that somehow the fix for this issue and #3280 exists in the DEV branch but is not being included in the releases.  No idea why.

**Comment by cwisniew** [comment]
@Phergus are you able to try this?
I am not able to reproduce with code in develop branch of 1.12 beta 3. Starting to wonder what I am doing wrong :)

**Comment by Phergus** [comment]
@cwisniew  Nope.  Tried with the campaign file originally provided and with the standalone .por file in both beta 3 and with current dev code.  No errors seen running melee attack macro.  No problems opening edit token dialog.

**Comment by adventuremagic123** [comment]
It's critical that you load the campaign BEFORE starting the server -- otherwise you won't see a problem.

**Comment by Phergus** [comment]
Yes.  I loaded the campaign before starting the server.

**Comment by adventuremagic123** [comment]
Very puzzling.  I can reproduce this everytime on different PCs.  I wonder if have Hero Lab installed makes a difference.  I'll try this tomorrow on a laptop where I don't have Hero Lab.

**Comment by adventuremagic123** [comment]
I don't know what the difference is between the environments on your PCs versus mine -- but I can reproduce this issue every time on 3 of my PCs with or without Hero Lab installed.

**Comment by adventuremagic123** [comment]
I just had a thought.  The most likely environment difference between my PCs and yours are the server start and preferences menu item settings.  The problem must be burried in one of those options.

I'll do some testing to see if I can find it.

@Phergus

**Comment by adventuremagic123** [comment]
These are the preferences I'm using on a PC where I am able to reproduce this problem:

![Screenshot 2022-09-18 110930](https://user-images.githubusercontent.com/50708405/190917079-2d32640d-4b1e-44a3-a888-c79e6dc7d7b6.JPG)

![Screenshot 2022-09-18 111139](https://user-images.githubusercontent.com/50708405/190917089-cc2bb06b-1bd7-4a99-a813-9751f2d9d09a.JPG)

![Screenshot 2022-09-18 111158](https://user-images.githubusercontent.com/50708405/190917098-af4a5087-024f-4f4d-9a8e-5ec761dbd3f9.JPG)

![Screenshot 2022-09-18 111225](https://user-images.githubusercontent.com/50708405/190917104-b1172f1f-ce09-4d2a-9823-c0826f034c22.JPG)

![Screenshot 2022-09-18 111248](https://user-images.githubusercontent.com/50708405/190917110-67ef2059-6813-4446-88cd-04b1eaa6332e.JPG)

![Screenshot 2022-09-18 111313](https://user-images.githubusercontent.com/50708405/190917117-92cf47e4-374a-47c0-8488-fd85cef379e1.JPG)

**Comment by adventuremagic123** [comment]
The MapTool.cfg I used to reproduce this problem is attached below (unzip the file):

[MapTool.zip](https://github.com/RPTools/maptool/files/9594398/MapTool.zip)

**Comment by adventuremagic123** [comment]
This is a big problem because I can reproduce it everytime also when I have a campaign loaded and stop the server.  If I forget to save my campaign before stopping the server, all of my Hero Lab tokens throw the exception I provided above and in the same way.

**Comment by adventuremagic123** [comment]
Just to be clear.  The work-around for this problem goes like this:

1. If you're planning on starting the server, load the campaign AFTER the server is started.

2. If you're planning on shutting down the server, save your campaign FIRST -- if you do it after all your Hero Lab tokens will be messed up as described above.

3. If you're simply developing a campaign and have no plans to start or shutdown the server, then there is no problem.
