### ISSUE TITLE
[Bug]: Draw Tool (and similar tools) sometimes just do not function at all for an instance of Maptool.

### ISSUE THREAD

**Issue by Ltheb** [RPTools/maptool#3686]
### Describe the Bug

Sometimes (Roughly 10% of the time), when Maptools is started, the bug is triggered.  
I am unaware of any specific condition that activates this bug, and will discuss it's frequency and conditional nuances in the "To Reproduce" section, below, but it seems to trigger on maptools launch, primarily. 

When the bug is triggered, Maptool seemingly functions normally, however, the Drawing tools and template tools become semi-unusable.

The tools can be selected, options toggled, texture/colors changed, drawing layers selected, etc. They appear to function normally until you actually start drawing.  

When you click to begin a drawing, it functions normally; If you intend to draw a rectangular area, you can start drawing an area. It gives the distance measurements and everything. But attempting to finished the drawing, IE Left-clicking to complete it does nothing. In fact, attempting to "complete" the drawing freezes it on the screen, where it exists, as if you were still attempting to draw it, until you attempt to draw something else, which causes the first failed attempt to vanish without a trace, like a ghost.  Additionally, moving the mouse over a macro in any macro panel (Selected and Campaign macros work with this) causes the ghost image to immediately vanish as well.
Nothing is ever drawn, and this bug is unfailing in its ability to prevent the user from drawing anything, with any drawing or template tool. Nothing appears in the draw explorer, ect. No amount of mode-switching or toggling or holding of any keys seems to fix this issue.  Using the CTRL, ALT, and SHIFT modifiers to the drawing tool seem to function as expected, but one cannot "confirm" the drawing attempt. The only fix to this glitched state is to restart maptools or to launch a server* (See the To-Reproduce section)

Saving the campaign while the bug is active does not seem to be a problem, and does not seem to corrupt the campaign file in any way that is noticeable, nor is anything attempted to be drawn saved in some way if the campaign file is saved, and then subsequently reloaded.  Loading a campaign in an unbugged maptool instance which was saved while the bug was active does not seem to save the bug.

### To Reproduce

This bug seems to be related to maptool's launch in some way.  In attempting to reproduce this bug, I was able to launch maptool almost a dozen times in a row without the bug.  It may also trigger on campaign file load, but that does not seem to happen often, and the bug seems to persist between different campaign files if you open differing files, and so seems linked to the instance of maptool.

The bug sometimes persists when the server is started, but not consistently. While looking up this bug (After being frustrated by it twice in a row), one user who seemed to have a similar sounding bug (But did not seem to report it properly on the discord server almost a year ago) claimed starting a server removed this bug.  I was able to reproduce this effect, but this is not always the case in my experience, and just two weeks ago recall having to restart a server mid-game, because I didn't check for the bug before beginning the game session.  Once the bug is cured in this way, it seems gone.

### Expected Behaviour

One would expect the drawing tool to, well, draw.

### Screenshots

![image](https://user-images.githubusercontent.com/66122919/192525427-9d40bc14-1cf0-488c-97b4-080b4294fc86.png)
This is an entirely unhelpful screenshot, but this is what it looks like.  I had "finished" drawing that rectangle of dirt, but it never "completed" its drawing attempt, and I was able to open up snipping tool, with the mouse, and get a screen shot of it doing this with ease.

### MapTool Info

Version: 1.11.5 (It happened as early back as 1.10 I think); New* install (I think some registry bits and config files lingered, but the installation folder is fresh)

### Desktop

Windows 10; Version 10.0.19043 Build 19043; (Obviously happened on earlier builds...)

### Additional Context

==== MapTool Information ====
MapTool Version: 1.11.5
MapTool Home...: C:\Users\{USER}\.maptool-rptools
MapTool Install: E:\D&D\Maptool\Maptool4\app
Max mem avail..: 3 GB
Max mem used...: 2 GB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\{USER}\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: E:\D&D\Maptool\Maptool4\runtime
Java Vendor....: Eclipse Foundation
Java Version...: 16.0.2
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  -Djpackage.app-path=E:\D&D\Maptool\Maptool4\MapTool.exe

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
PATH...........: E:\D&D\Maptool\Maptool4;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Plantronics\PlantronicsURE\;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Users\{USER}\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\{USER}\AppData\Local\Microsoft\WindowsApps;;E:\Programs\mitmproxy\bin;.
Number of Procs: 8

==== User Information ====
User Name: {USER}
User Home: C:\Users\{USER}
User Dir.: E:\D&D\Maptool\Maptool4

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Realtek PCIe GbE Family Controller
Interface Name: eth2
Address...: 192.168.1.2
Address...: fe80:0:0:0:c476:6760:2ffa:98af%eth2

Host Address...: 192.168.1.2
Default Gateway: 192.168.1.1

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

==== Internet Gateway Devices ====
Device Name.: Actiontec "Wireless Broadband Router"
Model Name..: "Wireless Broadband Router"
Manufacturer: Actiontec
Model Number: 40.21.24
Model Desc..: Actiontec "Wireless Broadband Router" Internet Gateway Device
Firmware....: Wireless Broadband Router/4.7.5.3.31.2.19 UPnP/1.0
External IP.: {IP Withheld}

**Comment by Phergus** [comment]
Are you running with the window maximized or using full-screen mode?

I notice you have a different Java version installed.  Do you have other applications that need that Java?  MapTool includes its own runtime.

**Comment by Ltheb** [comment]
It launches maximized.
I do have a need for java, unfortunately.  I have not tested if removing of that java version removes the problem.

**Comment by FullBleed** [comment]
I'm going to provide some really useless info here (if only in support of the fact that I think there is something suspect going on with the draw tools in certain circumstances)... Keep in mind, I don't use the drawing tools much.  But when I was testing the freehand drawing tool to try and figure out what was going on with overlays/map location/and scaling in MT I did run into the issue of the drawings not showing up sometimes.   Usually I'd just keep drawing and they'd eventually start to show up after I drew 5-6 shapes... but I have zero idea why it was happening and cannot reproduce the issue.  I figured it was perhaps a graphics driver issue on my side since I hadn't seen any drawing reports, so I paid it little attention (and I usually had like 4 copies of MT running at the same time.)

I don't have any other java installed and I believe I saw it happen in 1.11.5 and 1.12.x.

**Comment by Azhrei** [comment]
It may be helpful to have the log file under `MAPTOOL_LOGDIR`.

Also, can you try creating a new user id and install MT under that account?  IIRC, MT’s registry entries are per-user, not global, so this will determine whether any leftover registry entries are getting in the way.

**Comment by Ltheb** [comment]
I can do so, I think; It may take a bit to get it up and running and tested (due to the random nature in which this glitch strikes).  I shall report back any findings once I do so.

**Comment by Ltheb** [comment]
I was able to set up a new user account on my machine. DLing and re-running Maptool (Btw, the website, (https://www.rptools.net/toolbox/download-rptools-products/) labels a 1.12 version as 1.11; I found the 1.11.5 version to match my current, but that is another issue entirely).

Running on a new user, Maptool was unable, given about 20 attempts, to reproduce the bug. However, this does not seem too out of line with the issue I have experienced, since it seems to strike at random.

Also, I would upload log files from the LogDir location, but I feel I would need to scrub personal identifiers from them.  I took a peek into them, and could not identify any that directly corresponded to a bugged instance. However, there were some strange entries in a few of them such as:
"2022-09-27 06:09:04.447 INFO  net.rptools.maptool.client.ui.MapToolFrame - Removing the F10 key from the menuBar's InputMap; it did  exist"
"2022-09-27 06:24:54.277 INFO  net.rptools.maptool.client.ui.token.EditTokenDialog - Stopping autoGenerateVblSwingWorker..."
"2022-09-15 21:18:41.569 INFO  net.rptools.maptool.client.walker.astar.AbstractAStarWalker - vblGeometry is invalid! May cause issues. Check for self-intersecting polygons."
As well as a log file that had two  "Maptool Started!" headers, and repeated info, below (like mentioning all the UI themes being installed, going through the assets, then installing UI themes, again) about 3 seconds apart. 

Is there anything I should be looking for in these logs? I could try to catch a log file generated during one of the bugged sessions and scrub and upload that, though I was not able to identify anything from the logs during my attempts earlier this week when I set out to document this bug that seem different from any non-bugged log. Most of the weird stuff seems to be from logs when I load up a campaign file, but the bug occurs before that.

**Comment by Azhrei** [comment]
The main thing from the logs is exception traces (will include the word “exception” in them).  You may not see anything unusual unless the bug can be triggered.

You can go back to using your original account and just copy the log file to a new name after a session in which the bug appears (the log isn’t kept for each individual run, just the most recent).

**Comment by Ltheb** [comment]
[maptool log.txt](https://github.com/RPTools/maptool/files/9678831/maptool.log.txt)
Ok, I was able to get a log from the bug occuring. I think it might* be related to this line: 
2022-09-29 16:10:05.052 WARN  net.rptools.clientserver.simple.AbstractConnection - message received but not messageHandlers registered.
However, I cannot be sure; nothing else about the log seems out of place.

**Comment by Ltheb** [comment]
I can now confirm this bug persists within 1.12.2, and with a higher frequency.  I can additionally note additional symptoms here.  In addition to the inability to draw with just about any shape, shapes drawn by others also disappear.  The bug seemed to come and go during a session I ran, and while it was inactive, I could draw properly, but once it activated, I was unable to see shapes drawn while it was not active.  The shapes drawn did not disappear from the draw explorer, but double-clicking on them zoomed the map to the 0,0 coordinates of the drawn shape instead of the location of the (now-invisible) previously drawn shape.  

Shapes drawn in previous sessions persisted normally unless the bug was triggered during that session, which either causes drawing them to seem impossible, or for them to disappear afterwards a few minutes later.  The bugged images do, however, seem to save, and are visable in subsequent loadings of maptool.

**Comment by kwvanderlinde** [comment]
I tried to reproduce this issue quickly, but haven't luck yet. But I think you're right about these being two separate bugs.

For Bug 1, I don't think this has anything to do with autosave, but maybe there's some wierd interaction going on. I dug through the drawing completion code and found out that a missing connection will cause exactly the symptoms you describe (as would a couple other cases, but I doubt they apply). A missing connection is a problem even when not explicitly running a server, because we still create a personal server with a connection for that case, and expect the connection to be present.  _For anyone interested in internals, it's as if [this line](https://github.com/RPTools/maptool/blob/1.12.2/src/main/java/net/rptools/maptool/client/tool/drawing/AbstractDrawingTool.java#L362) doesn't run, or really if [this much deeper check](https://github.com/RPTools/maptool/blob/1.12.2/src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java#L517-L519) never passes._ In that case, the drawing ends up in the zone's undo list, but never gets properly added to the zone itself. The only reason the drawing seemingly hangs around is that a new frame hasn't been rendered yet, but any update to the zone would passed that. This particular issue could be solved by directly adding to the zone instead of relying on the server message to do it, as is done for many other operations. But if this really is the situation, it would also be good to figure out why there might not be a connection object present.

I don't have anything on Bug 2 yet (haven't had a change to dig into it). Not sure how autosave would play into that, but my intuition says there's a race with the autosave campaign copying, probably with updates coming from server message handling...? _Oh, I just noticed that the `ServerMessageHandler` doesn't run its handling on the main thread. Compare with `ClientMessageHandler` which generally does. And `AutoSaveManager` always runs the autosave on the main thread. So maybe there is some merit to what I thought was a long shot ... Needs a closer look yet._

**Comment by Azhrei** [comment]
The autosave does not make a copy of everything, it just copies references.

When the Campaign object is copied, it contains references to the original Zone objects.  Those objects can continue to be updated while the autosave is executing, making the saved file useless if a conflicting change is made to a Zone at the same time the save is scanning that Zone.

The classic solution for something like that is to process all changes to a Zone in a queue and freeze the queue while the autosave is running.  (Meaning that new commands can be added to the queue, but not persisted to the Zone until unfrozen.)  The current MapTool architecture makes this almost impossible.

One way to cheat might be to copy the Zones as well as the Campaign object, but the Zones carry _a lot_ of data with them and that could be time prohibitive...

**Comment by kwvanderlinde** [comment]
That's not accurate. The auto-save uses Campaign's ["copy constructor"](https://github.com/RPTools/maptool/blob/develop/src/main/java/net/rptools/maptool/model/Campaign.java#L179-L186), which implements a mostly deep copy. Each Zone _is_ being copied, and each Zone in turn copies their contents as well, including the drawings.

**Comment by Azhrei** [comment]
Oh, does it??  That's great.  I don't remember the copy constructor doing that.  My bad.  (I'll go back and edit my previous post to clarify.  Thanks.)

**Comment by kwvanderlinde** [comment]
I also have a correction to make :smile: Yes, it's a deep copy, and the Zones do copy their lists of drawings, but the drawings themselves aren't being copied. Thats... probably? ... not the cause of this particular issue, but now I need to file another bug report ...

**Comment by Ltheb** [comment]
I have an update on the drawing tool bug; Specifically, the one in which attempting to draw a shape cannot "complete" the shape, and the drawing too becomes impossible to use.

I was attempting to work on a map, when I noticed the bug was in effect by drawing some shapes but seeing them incomplete.  I went to start up a live server, having some success with that causing the bug to de-manifest.  However, I still had an unfinished, uncommited shape still active on my cursor;  Maptools threw two errors.   One was in an unresponsive error window, which I will attach an image of here, since I could not select the text from.  It came up first.  The other was a more traditional error window, which I managed to snag the text from.  

The first window:
![Error1](https://user-images.githubusercontent.com/66122919/226098233-9ff753b8-1aa8-4458-8f5f-8bbf9948d645.JPG)

The second window's text: 

`java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.model.Zone.addDrawable(net.rptools.maptool.model.drawing.DrawnElement)" because "zone" is null
	at net.rptools.maptool.client.ClientMessageHandler.lambda$handle$51(ClientMessageHandler.java:923)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
`

I hope this information is helpful in any queries as to this very show-stopping bug; Its the first real error I've been able produce with it, so I do hope it is related.

**Comment by kwvanderlinde** [comment]
I just encountered an issue that seems related and may have the same root cause. In my case, I connected a second MT instance as a GM client, then switched to a map with several drawings. Immediately I was not able to use the Draw Explorer - the layers would show, but I could not expand them or even give focus to the Draw Explorer. At the same time, if I tried to draw on the map, it was not possible. Otherwise, MT seemed to function fine and was responsive.

But once I closed the Draw Explorer, my attempted drawings suddenly spawned in. And once I opened the Draw Explorer again, it functioned just fine as well. This leads me to believe there is somehow a deadlock between the Draw Explorer and the drawing tools, though I'm surprised it didn't affect more.

This is on 1.15.2.
