### ISSUE TITLE
Exception in thread "Thread-7" com.caucho.hessian.client.HessianConnectionException

### ISSUE THREAD

**Issue by friend8** [RPTools/maptool#37]
I'm using maptools on a server where it runs 24/7. The only problems are the connection losses to the maptools registry webservice.
It would be really nice, if it simply tries to reconnect instead of crashing. This also causes the changes to the current loaded campaign to be completely lost.
Below you can find the error/exception message that I receive.

```
Exception in thread "Thread-7" com.caucho.hessian.client.HessianConnectionException: 500: java.io.IOException: Server returned HTTP response code: 500 for URL: http://services.rptools.net/maptool_registry-1_3.php
        at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:197)
        at com.sun.proxy.$Proxy0.heartBeat(Unknown Source)
        at net.rptools.maptool.client.MapToolRegistry.heartBeat(MapToolRegistry.java:65)
        at net.rptools.maptool.server.MapToolServer$HeartbeatThread.run(MapToolServer.java:192)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://services.rptools.net/maptool_registry-1_3.php
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1677)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1673)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1246)
        at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:179)
        ... 3 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://services.rptools.net/maptool_registry-1_3.php
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:168)
        ... 3 more
```

**Comment by Azhrei** [comment]
Thank you for the stack trace.

I agree with you regarding some flexibility in the handling of the heartbeat.

I think I've looked at this in the past and determined that the heartbeat couldn't be replaced with a "fake" replacement that just said it was always online as there were other sections of the code that depended on it.  However, I don't recall the specifics right now and maybe when I looked at it before I just didn't see an obvious answer.  If no one else jumps on it, I'll take another look.

HTTP 500 (and similar, non-permanent) error codes should simply trigger a retry in a smaller window that gradually grows larger, up to some upper limit.  The 500 code is probably a server overload.

**Comment by friend8** [comment]
Seems like nobody is willing to look into this.
The error occurred multiple times in the last two weeks and this is really annoying if you have to restart the campaign several times.

**Comment by rkathey** [comment]
Generally, visibility for these problems are discussed on the on the
MapTool forums.  http://forums.rptools.net
Someone there might be able to help.

**Comment by Azhrei** [comment]
I've made some changes to correct this.  The change is committed and I'm going to do some testing tomorrow.

The implementation produces a popup on the server system (and an entry to the log and the chat window) and a "/gm" message to all GMs when it happens the first time.  Subsequent occurrences cause a chat message to go to the server system and all GMs, but nothing to the log.

This means you'll be notified when it happens and be kept informed, but you can choose to ignore the chat messages, if you like.  I'm not sure what the text will say yet, but it will include the number of heartbeat pulses that have failed.

**Comment by Azhrei** [comment]
Opinions on the technique discussed here are welcome!

Here's the message that appears in the popup on the MT server:

**Connection refresh to the MapTool registry failed.<br/>The registry server will purge records periodically, making it difficult for future clients to connect.<br/>If this persists, you will need to provide clients with your contact information directly (IP address {0} and port {1}).**

It only appears once, the first time the heartbeat fails after starting a server.  The same text also appears in the MapTool log.  However, the following messages are written to the chat windows of the MT server and all GMs (using the equivalent of "/me" and "/gm") each time a failure occurs:

**Connection refresh to the MapTool registry failed.<br/>The registry server will purge records periodically, making it difficult for future clients to connect.<br/>If this persists, you will need to provide clients with the server information directly (IP address {0} and port {1}).**

When the connection comes back, this message is sent to the same chat windows:

**Connection refresh to the MapTool registry succeeded (but failed in the past).<br/>As long as success is maintained, you will not see this message again.**

In situations where the heartbeat works, then fails, then works again, the popup only appears once, but the chat messages will appear to indicate whether the last contact to the registry was successful or not.  In order to not spam users continuously, chat messages will be throttled such that they never occur more than once in a 15 minute window when continuous failures occur, and that time window lengthens to 45 minutes, then 70 minutes (the largest value), resetting back to 15 minutes when a successful connection is made.

The registry's purpose is to allow clients to connect easily (without needing the IP address and port) so the use of the registry is not required at all and the _RPTools Alias_ field can be left empty when starting a server and no heartbeat will be created.
