### ISSUE TITLE
[Bug]: The "look here" pointer does not always restore the players' view

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3733]
### Describe the Bug

When a GM holds down `ctrl+shift`, then presses `space`, a pointer appears on the map and forces the player views to be centered on that point. When `space` is released, the player views go back to where they were. But if `ctrl` or `shift` is released before `space`, the view is not restored.

### To Reproduce

1. Start a server on a first instance of MapTool
2. Start a second instance and connect to the server.
3. As the GM on the server, press `ctrl+shift+space` while the cursor is over the map. Observe that the player view moves to center  that point.
4. Release `ctrl` (or `shift`), then release `space`. Observe that the pointer disappears, but the player view is not restored.

### Expected Behaviour

Player views should always be restored when the GM is done using the "look here" pointer.

### Screenshots

This is the pointer I'm referring to:
![image](https://user-images.githubusercontent.com/7492219/200083681-2d3573fb-8cb0-4edb-89bd-6d3d1baf0f83.png)

### MapTool Info

1.11.5, also seen on 1.12.2

### Desktop

Linux mint 21

### Additional Context

A similar issue happens the other way around. Let's say we start with just `ctrl+space` as the GM, to make a speech bubble show. Then we also hold down `shift` before letting go of `space`. This either results in the player's view jump for no reason (if there was a previous use of the "look here" pointer) or causes a NPE:
<details>
<summary>
java.lang.NullPointerException: Cannot read field "x" because "point" is null
</summary>
<pre>
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.centerOn(ZoneRenderer.java:640)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.restoreView(ZoneRenderer.java:804)
	at net.rptools.maptool.client.ClientMethodHandler.lambda$handleMethod$2(ClientMethodHandler.java:441)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre>
</details>

**Comment by FullBleed** [comment]
I didn't even know about the "force to view" option/feature of the pointers (but use the space pointer often)... I think I might need to hotkey those keybindings to some buttons on my mouse or gamepad (after you fix this). ;)

Very useful!

**Comment by kwvanderlinde** [comment]
Just added it to the [Shortcuts Keys](https://wiki.rptools.info/index.php/Shortcut_Keys#Map_Related) wiki page as it was missing.

Speaking of the wiki, [another page](https://wiki.rptools.info/index.php/MapTool_User_Interface#Controls_in_the_Map_View) does already describe this pointer:
> If used by the GM, this illustrated pointer also moves the map view of all players on the same map to center on the pointing location and the GM's zoom level. When used in this way, the GM can release the spacebar first to let player views 'snap back' to their previous view, or release either Shift or Meta first to keep the player views centered on the new location.

So this is documented behaviour, but I don't think it is desirable. If we actually want to change the players' views permanently, we can use things like **Center Players on Current View** ( `ctrl+f`) or similar. IMO the "look here" pointer is only compelling if I know I won't _accidentally_ yank the players somewhere they don't want to be.

**Comment by FullBleed** [comment]
I get why it does it that way... but that key release order method is not a fun UI.

I never thought much about what my pointer was doing to the player's view... I just assumed they could only see the pointer if it was on their screen because sometimes they *don't* see it (and that's always been annoying because if I'm using it I'm pointing out something important).

So my players are about to get the "yank and stay" method now that I know about this.  And I'm going to blame kwvanderlinde for letting me know about it if they complain.  ;)

The real "fix" for whether or not a player would have a problem staying or going back to where they were would probably need to require some "choice" for the player.  Could something more interactive be done... like:

GM points, players are snapped to the location to see what they are pointing to, when the GM releases the pointer it changes to a "return icon" center scree and stays on the screen on the screen for a few seconds, if a player clicks the "return icon" they go back to where they were before the GM initiated the pointer, click anywhere else and it disappears immediately.
