### ISSUE TITLE
[Bug]: Adding/Editing state with dot produces java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3844]
### Describe the Bug

Adding/Modifying a state with a dot in the lower-right quadrant produces java.lang.IllegalArgumentException

### To Reproduce

Go to campaign properties states tab
Pick a state with a dot in the lower-right quadrant
Try to modify it's name
or try to create same

### Expected Behaviour

States update cleanly

### MapTool Info

Dev 12.2.something

### Desktop

Win10

### Additional Context

```
java.lang.IllegalArgumentException: No enum constant net.rptools.maptool.model.drawing.AbstractTemplate.Quadrant.Bottom Right
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at net.rptools.maptool.model.drawing.AbstractTemplate$Quadrant.valueOf(AbstractTemplate.java:114)
	at net.rptools.maptool.client.ui.campaignproperties.TokenStatesController.createTokenOverlay(TokenStatesController.java:704)
	at net.rptools.maptool.client.ui.campaignproperties.TokenStatesController.actionPerformed(TokenStatesController.java:311)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
...
```

**Comment by Phergus** [comment]
Also applies to Corner Image state types.
