### ISSUE TITLE
[Bug]: Tokens generating NullPointerException error on 1.13.0 using campaign created in previous public version (1.12.2)

### ISSUE THREAD

**Issue by Alexpop11** [RPTools/maptool#4037]
### Describe the Bug

Using a campaign file that was created with the previous version of maptool, placing a .png on the map (and therefore creating a token) generates the following error:

`java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.max(Unknown Source)
	at net.rptools.maptool.client.ui.zone.ZoneView.illuminationKeyFromView(ZoneView.java:443)
	at net.rptools.maptool.client.ui.zone.ZoneView.getIllumination(ZoneView.java:514)
	at net.rptools.maptool.client.ui.zone.ZoneView.getVisibleArea(ZoneView.java:616)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderVisionOverlay(ZoneRenderer.java:1712)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderGMVisionOverlay(ZoneRenderer.java:1704)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1335)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:822)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

### To Reproduce

1. Open previously existing campaign from Maptool 1.12.2
2. Create new default map
3. Drag and drop PNG file into maptool map, on Token layer
4. hover mouse over token

### Expected Behaviour

No errors, as with the previous version

### Screenshots

![Screenshot 2023-05-06 155127](https://user-images.githubusercontent.com/22580171/236643979-6d120bb0-7cbd-4888-b3f0-84ef471170f8.jpg)

### MapTool Info

Version 1.13.0 Upgrade [1.12.2]

### Desktop

Windows 11

**Comment by Azhrei** [comment]
Potential issue with lighting? @kwvanderlinde

**Comment by kwvanderlinde** [comment]
This doesn't look to be related to upgrading specifically. Here's an alternative reproduction:
1. Start a new campaign in 1.13.0
2. Edit > Campaign Properties, Sight tab, delete the "Normal" vision and hit "OK"
3. Drag an image onto the Token layer.
4. Hover over the token to get a NPE

What happens is that - until a token is edited - it defaults to a sight type of "Normal", regardless of whether the campaign actually has such a sight type. And there's one place where I missed that possibility, causing the NPE.

**Comment by Pmofmalasia** [comment]
Fixed for me using the reproduction method (deleting "Normal" vision) in 1.13.2.

**Comment by JarieSuicune** [comment]
Same. With the latest update I haven't had any troubles with this.
