### ISSUE TITLE
[Bug]: 1.13.1 complains about missing libzstd-jni

### ISSUE THREAD

**Issue by tomlowshang** [RPTools/maptool#4120]
### Describe the Bug

Maptool log:
```
2023-06-11 11:03:47.167 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2023-06-11 11:03:47.232 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2023-06-11 11:03:47.233 INFO  net.rptools.maptool.client.MapTool - **                              MapTool Started!                              **
2023-06-11 11:03:47.234 INFO  net.rptools.maptool.client.MapTool - **                                                                            **
2023-06-11 11:03:47.234 INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
2023-06-11 11:03:47.235 INFO  net.rptools.maptool.client.MapTool - Logging to: /home/tlow/.maptool-rptools/logs/maptool.log
2023-06-11 11:03:47.236 INFO  net.rptools.maptool.client.MapTool - getting MapTool version from manifest: 1.13.1
2023-06-11 11:03:47.236 INFO  net.rptools.maptool.client.MapTool - getting MapTool vendor from manifest:  RPTools
2023-06-11 11:03:47.317 INFO  net.rptools.maptool.client.MapTool - argument passed via command line: -v=1.13.1
2023-06-11 11:03:47.318 INFO  net.rptools.maptool.client.MapTool - overriding MapTool version from command line to: 1.13.1
2023-06-11 11:03:47.319 INFO  net.rptools.maptool.client.MapTool - MapTool vendor: RPTools
2023-06-11 11:03:50.135 INFO  net.rptools.maptool.client.ui.MapToolFrame - Removing the F10 key from the menuBar's InputMap; it did  exist
2023-06-11 11:03:51.115 INFO  net.rptools.maptool.server.ClientHandshake - GM Tom sent: CLIENT_INIT_MSG
2023-06-11 11:03:51.140 ERROR net.rptools.maptool.client.swing.MapToolEventQueue - java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni-1.5.5-315076781833375798468.so: /tmp/libzstd-jni-1.5.5-315076781833375798468.so: failed to map segment from shared object
no zstd-jni-1.5.5-3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni-1.5.5-3.so or load zstd-jni-1.5.5-3 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.5-3 in your system.
java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni-1.5.5-315076781833375798468.so: /tmp/libzstd-jni-1.5.5-315076781833375798468.so: failed to map segment from shared object
no zstd-jni-1.5.5-3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni-1.5.5-3.so or load zstd-jni-1.5.5-3 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.5-3 in your system.
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[?:?]
	at java.lang.System.loadLibrary(Unknown Source) ~[?:?]
	at com.github.luben.zstd.util.Native$1.run(Native.java:69) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at com.github.luben.zstd.util.Native$1.run(Native.java:67) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at com.github.luben.zstd.util.Native.loadLibrary(Native.java:67) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at com.github.luben.zstd.util.Native.load(Native.java:154) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at com.github.luben.zstd.util.Native.load(Native.java:85) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.<clinit>(ZstdOutputStreamNoFinalizer.java:18) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at com.github.luben.zstd.ZstdOutputStream.<init>(ZstdOutputStream.java:75) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at com.github.luben.zstd.ZstdOutputStream.<init>(ZstdOutputStream.java:55) ~[zstd-jni-1.5.5-3.jar:1.5.5-3]
	at org.apache.commons.compress.compressors.zstandard.ZstdCompressorOutputStream.<init>(ZstdCompressorOutputStream.java:87) ~[commons-compress-1.22.jar:1.22]
	at net.rptools.clientserver.simple.AbstractConnection.compress(AbstractConnection.java:87) ~[MapTool.jar:1.13.1]
	at net.rptools.clientserver.simple.AbstractConnection.addMessage(AbstractConnection.java:79) ~[MapTool.jar:1.13.1]
	at net.rptools.clientserver.simple.client.SocketClientConnection.sendMessage(SocketClientConnection.java:75) ~[MapTool.jar:1.13.1]
	at net.rptools.clientserver.simple.client.SocketClientConnection.sendMessage(SocketClientConnection.java:71) ~[MapTool.jar:1.13.1]
	at net.rptools.maptool.server.ClientHandshake.sendMessage(ClientHandshake.java:134) ~[MapTool.jar:1.13.1]
	at net.rptools.maptool.server.ClientHandshake.startHandshake(ClientHandshake.java:127) ~[MapTool.jar:1.13.1]
	at net.rptools.maptool.client.MapToolConnection.start(MapToolConnection.java:81) ~[MapTool.jar:1.13.1]
	at net.rptools.maptool.client.MapTool.createConnection(MapTool.java:1207) ~[MapTool.jar:1.13.1]
	at net.rptools.maptool.client.MapTool.startPersonalServer(MapTool.java:1174) ~[MapTool.jar:1.13.1]
	at net.rptools.maptool.client.MapTool.initialize(MapTool.java:675) ~[MapTool.jar:1.13.1]
	at net.rptools.maptool.client.MapTool.lambda$main$9(MapTool.java:1788) ~[MapTool.jar:1.13.1]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54) [MapTool.jar:1.13.1]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
```

### To Reproduce

Run Maptool on Debian unstable.

### Expected Behaviour

Maptool includes all required libraries.

### MapTool Info

1.13.1 installed from .deb package.

### Desktop

Debian sid/unstable

**Comment by mal-w** [comment]
Related to #4083...

If you open a terminal and run the following, what do you get?

```bash
zstd --version
```

I suspect it tells you `zstd not found`..

If it does the quick fix for you would be to do the following then try running maptool again
```bash
sudo apt install zstd
```

**Comment by tomlowshang** [comment]
zstd is installed.
```
$ zstd --version
*** Zstandard CLI (64-bit) v1.5.4, by Yann Collet ***
```

**Comment by mal-w** [comment]
Ok then the issue is more complicated and probably to do with the new dependency on https://github.com/luben/zstd-jni.. I can't help more than that but maybe @thelsing can?

**Comment by tomlowshang** [comment]
I figured it out. My /tmp is mounted with noexec flag which prevents the .so from running there. It works if I pass `-Djava.io.tmpdir=/path/to/dir` on the command line or via the JAVA_TOOL_OPTIONS environment variable. Java doesn't use the standard TMPDIR variable.

Sorry for the noise.
