### ISSUE TITLE
[Bug]: Unable to open campaigns with JAR build

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4355]
### Describe the Bug

It is no longer possible to open campaigns as a `NullPointerException` is thrown after selecting the campaign file.

### To Reproduce

1. Run the JAR file with this lovely command (optiosn taken from the jpackage options):
```
java -Djpackage.app-version=1.0 -Xss8M -Dsun.java2d.d3d=false -Dsentry.environment=Production -Dfile.encoding=UTF-8 -Dpolyglot.engine.WarnInterpreterOnly=false -Djava.util.Arrays.useLegacyMergeSort=true -DMAPTOOL_DATADIR=.maptool-rptools -XX:+ShowCodeDetailsInExceptionMessages --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED -jar MapTool-1.14.0-rc.4.jar -v='1.14.0'
```
2. Attempt to open a campaign, say, from the Recent Campaigns list.
3. A dialog will come up showing a NPE.

### Expected Behaviour

Campaign files should open without throwing errors when using the published JAR.

### MapTool Info

1.14.0-rc.4

### Desktop

Linux Mint 21

### Additional Context

Here is the complete error message shown in the dialog:
<details>
<pre>
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
	at net.rptools.maptool.client.AppUtil.getInstallDirectory(AppUtil.java:219)
	at net.rptools.maptool.client.AppActions.loadCampaign(AppActions.java:2559)
	at net.rptools.maptool.client.AppActions$OpenMRUCampaign.actionPerformed(AppActions.java:3595)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

</pre>
</details>

And my debug info:
<details>
<pre>
==== MapTool Information ====
MapTool Version: 1.14.0
MapTool Home...: /home/kenneth/.maptool-rptools
MapTool Install: /home/kenneth/tmp
Max mem avail..: 15 GB
Max mem used...: 480 MB
Custom Property: -DMAPTOOL_LOGDIR=/home/kenneth/.maptool-rptools/logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /home/kenneth/.jdks/liberica-20.0.1
Java Vendor....: BellSoft
Java Version...: 20.0.1
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -Djava.util.Arrays.useLegacyMergeSort=true
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

==== OS Information ====
OS Name........: Linux
OS Version.....: 6.2.0-34-generic
OS Architecture: amd64
PATH...........: /home/kenneth/miniconda3/condabin:/home/kenneth/.poetry/bin:/home/kenneth/.local/bin:/home/kenneth/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kenneth/.local/share/JetBrains/Toolbox/scripts:/home/kenneth/bin:/home/kenneth/.local/bin:/home/kenneth/go/bin/
Number of Procs: 6

==== User Information ====
User Name: kenneth
User Home: /home/kenneth
User Dir.: /home/kenneth/tmp

==== Network Interfaces ====
Display Name..: ztzlgjggbh
Interface Name: ztzlgjggbh
Address...: fe80:0:0:0:44f6:e7ff:fecd:96b%ztzlgjggbh
Address...: 10.144.224.214

Display Name..: zt44xpuk3a
Interface Name: zt44xpuk3a
Address...: fe80:0:0:0:cd4:7eff:fec1:189b%zt44xpuk3a
Address...: 10.147.17.47

Display Name..: zthnhauxdb
Interface Name: zthnhauxdb
Address...: fe80:0:0:0:547f:6fff:fe98:c47a%zthnhauxdb
Address...: 10.147.18.47

Display Name..: wlp4s0
Interface Name: wlp4s0
Address...: fe80:0:0:0:849f:6e33:aac9:dc36%wlp4s0
Address...: 2001:569:5585:1900:9f80:165c:409d:3050%wlp4s0
Address...: 192.168.1.75

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.1.254

==== Locale Information ====
Country.: Canada
Language: English
Locale..: English (Canada)
Variant.: 

==== Encoding Information ====
Default Locale:   en_CA
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 3
Display 1: 7680x1440(-1)
Display 2: 2560x1440(-1)
Display 3: 2560x1440(-1)

==== Internet Gateway Devices ====
	No IGDs Found!
</pre>
</details>

**Comment by kwvanderlinde** [comment]
Hit this with a debugger, what's happening is that I'm running the JAR from a directory that does not have "maptool" in the path anywhere (in this case, it's `/home/kenneth/tmp`). So [this loop](https://github.com/RPTools/maptool/blob/1.14.0-rc.4/src/main/java/net/rptools/maptool/client/AppUtil.java#L218-L223) eventually gets to the point where `path` is the root directory (`/`), in which case `getFileName()` returns `null`.

The workaround for now is therefore to run the JAR from somewhere with a `*maptool*` parent directory.

**Comment by kwvanderlinde** [comment]
Tested on a new JAR I built off latest `release-1.14` (38e1469a0). Now able to open campaigns regardless of which directory the JAR is run from.
