### ISSUE TITLE
[Bug 1.14.0]: Terrible HTML breaks chat with constant error popup.

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#4498]
### Describe the Bug

Sending bad html to chat causes `java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0` error.

### To Reproduce

Put this code in to a macro in the Campaign Window
```
[H: output = "
<html>
<b>Advanced Creature (CR +1)</b><br>
Creatures with the advanced template are fiercer and more powerful than their ordinary cousins.<br>
Rebuild Rules: <b>AC</b> increase <b>natural armor</b> by +2; <b>Ability Scores</b> +4 to all ability scores.<br>
<table><thead>
<caption>Advanced Creature Abilities
<tbody>
<tr><th>Ability<th>Bonus
<tbody>
<tr><td>Strength<td>+4
<tr><td>Constitution<td>+4
<tr><td>Dexterity<td>+4
<tr><td>Intelligence<td>+4
<tr><td>Wisdom<td>+4
<tr><td>Charisma<td>+4
</table>"]
[R: output]
```
Run macro.

You'll get the error and when you mouse over chat text it'll repeat the error. You can stop it by entering /clr in the chat text entry form.

I've tried other variations of "bad html" without getting the error and I'm not sure what specifically causes the issue.

### Expected Behaviour

No error popup.

### Screenshots

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.desktop/javax.swing.text.html.TableView$RowView.layoutMajorAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.FlowView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.updateChildSizes(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(Unknown Source)
	at com.formdev.flatlaf.ui.FlatEditorPaneUI.getPreferredSize(FlatEditorPaneUI.java:226)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JEditorPane.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.desktop/java.awt.Container.layout(Unknown Source)
	at java.desktop/java.awt.Container.doLayout(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validate(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$3.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.displayPopup(MapToolEventQueue.java:111)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:73)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.displayPopup(MapToolEventQueue.java:111)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:73)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

### MapTool Info

1.14.0 rc2, 1.14.1 (works in 1.13.2)

### Desktop

Windows 11

**Comment by Azhrei** [comment]
The first `tbody` should probably be `thead` and the existing `thead` should be deleted.  (The `caption` element is in the wrong spot.)

No idea why that causes the Java HTML engine to freak out, though.

**Comment by bubblobill** [comment]
Close but no cigar.
`THEAD` &`TBODY` are invalid [HTML tags](https://www.htmlhelp.com/reference/wilbur/table/table.html)

`TBODY` appears to be the culprit.

**Comment by Azhrei** [comment]
Interesting!  I never noticed that!  Of course, the Swing HTML support should ignore any element it doesn't understand, but maybe not...?
