### ISSUE TITLE
[Bug]: Unexpected error when creating a new campaign or opening a campaign if [Map-> Adjust Grid…] box is open

### ISSUE THREAD

**Issue by Baaaaaz** [RPTools/maptool#4523]
### Describe the Bug

If the [Map-> Adjust Grid…] box is open when creating a new campaign or opening an existing campaign, an unexpected error occurs and if the warning dialog 'X' is clicked it will then show an empty warning dialog, which then requires clicking the dialog 'X' again.

java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.model.Zone.getGrid()" because "zone" is null
	at net.rptools.maptool.client.ClientMessageHandler.lambda$handle$19(ClientMessageHandler.java:531)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.displayPopup(MapToolEventQueue.java:111)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:73)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

### To Reproduce

Start MapTool
Toolbar [Map -> Adjust Grid…]
Toolbar [File -> New Campaign] or [File -> Open Campaign... and open an existing campaign file] 
Discard Current Campaign Confirmation Dialog [Yes]
Unexpected Error Warning dialog displayed.
If the warning dialog 'X' is clicked it will then show an empty warning dialog and you then have to click the  warning dialog 'X' again.

### Expected Behaviour

Gracefully handles opening the campaign file, or creating a new campaign without raising an error.

### Screenshots

Unexpected Error Warning Dialog
![image](https://github.com/RPTools/maptool/assets/131240480/7f8385a9-7913-46b3-80f0-fd41ae0db85b)

Empty Warning Dialog
![image](https://github.com/RPTools/maptool/assets/131240480/d23ce518-491d-4b2e-8497-189b07330f30)

### MapTool Info

Occurs in 1.13.2 & 1.14.3

### Desktop

Windows

**Comment by Baaaaaz** [comment]
Tested in 1.16.0.rc-2 and looks fixed to me.  Thanks!
