### ISSUE TITLE
[Bug]: Java Exception when Editing Campaign Token Properties

### ISSUE THREAD

**Issue by ColdAnkles** [RPTools/maptool#4650]
### Describe the Bug

Moving to edit a property in Token Type 2 while default value of a property is selected in Token Type 1 produces a java.lang.IndexOutOfBoundsException until you return to Token Type 1 and deselect it.

### To Reproduce

1. Go to Campaign Properties
2. Create a second Property Type with a test property alongside the default Basic Property Type
3. On the Basic Property Type, select the Text Field in the Default Column for any property - there should be a flashing cursor in the text box.
4. Select the new testing property type and attempt to select the Text Field in the Default Column

### Expected Behaviour

Moving to a different property type should deselect any text fields.

### MapTool Info

1.14.3

### Desktop

Windows

### Additional Context

java.lang.IndexOutOfBoundsException: Index: 4, Size: 1
	at java.base/java.util.LinkedList.checkElementIndex(Unknown Source)
	at java.base/java.util.LinkedList.get(Unknown Source)
	at net.rptools.maptool.client.ui.campaignproperties.TokenPropertiesTableModel.setValueAt(TokenPropertiesTableModel.java:126)
	at java.desktop/javax.swing.JTable.setValueAt(Unknown Source)
	at java.desktop/javax.swing.JTable.editingStopped(Unknown Source)
	at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)
	at java.desktop/javax.swing.AbstractCellEditor.stopCellEditing(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.ui.campaignproperties.CampaignPropertiesDialog.setVisible(CampaignPropertiesDialog.java:91)
	at net.rptools.maptool.client.AppActions$74.executeAction(AppActions.java:3052)
	at net.rptools.maptool.client.AppActions$ClientAction.execute(AppActions.java:3426)
	at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:3458)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by maltedreschert** [comment]
@cwisniew I have a fix for this bug. Please assign this issue to me, so I can send in a PR.

**Comment by thelsing** [comment]
@maltedreschert You can create PRs even if you are not assigned to the issue.

**Comment by maltedreschert** [comment]
@thelsing thanks for the hint. I did not want to step on anyone's toes or create duplicated work.

**Comment by FullBleed** [comment]
> @thelsing thanks for the hint. I did not want to step on anyone's toes or create duplicated work.

I don't think getting assigned for smaller/older issues is terribly important (unless they are the kind of issue that generated a lot of feedback)... but I think it's a reasonable idea, in the absence of an assignment, to go ahead and drop a post in the issue's thread to let people know you plan on working on it if you are so inclined.  That way anyone that's following the issue probably gets a notification just in case there is ongoing, unassigned work going on.  You might even get some additional context.

I think assignment is generally used for complicated features, showstoppers, and heavily commented/discussed issues (where there are many possible approaches).

I also think it's good for "new" devs to request assignment (like you have) to engage the managing infrastructure for any commentary about the process or particular issue you're interested in tackling.  Craig will certainly let you know if he's got a problem with your PR... and, so far, it doesn't appear that he's had any issue with your contributions.   ;)  

Soldier on!

PS:  There is a Dev channel on the Discord that will probably get you quicker dev feedback should you desire it: https://discord.com/channels/296230822262865920/494598206626463755
