### ISSUE TITLE
[Bug]: Error adding add-on with new stat-sheet

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4707]
### Describe the Bug

Added a new stat-sheet to my existing stat-sheet add-on.
Sheet details added to stat_sheets.json. 
Path to sheet is that same as all the others and the file name is correct.
Log details below

### To Reproduce

[stat_sheets.mtlib.zip](https://github.com/RPTools/maptool/files/14368881/stat_sheets.mtlib.zip)
Add this file as an add-on.
Produces an invalid location error.

### Expected Behaviour

Expected it to load just fine.
Loads fine on 1.14.0-a3
Bugs out on 1.15.0b1

### MapTool Info

1.15.0b1

### Desktop

Win10

### Additional Context

2024-02-22 12:37:39.081 ERROR net.rptools.maptool.model.library.addon.AddOnLibrary - Error adding stat sheet Rev-Compact, namespace rev.rptools.statsheets
2024-02-22 12:37:39.082 ERROR net.rptools.maptool.client.MapTool - Error adding stat sheet Rev-Compact, namespace rev.rptools.statsheets
java.io.IOException: Invalid Location
	at net.rptools.maptool.model.library.addon.AddOnLibrary.readAsString(AddOnLibrary.java:493) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.model.library.builtin.ClassPathAddOnLibrary.readAsString(ClassPathAddOnLibrary.java:76) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.model.library.Library.readAsHTMLContent(Library.java:96) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.model.sheet.stats.StatSheetManager.addStatSheet(StatSheetManager.java:153) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.model.library.addon.AddOnLibrary.registerSheets(AddOnLibrary.java:624) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.model.library.addon.AddOnLibrary.initialize(AddOnLibrary.java:579) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.model.library.addon.AddOnLibraryManager.registerLibrary(AddOnLibraryManager.java:82) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.model.library.LibraryManager.reregisterAddOnLibrary(LibraryManager.java:199) ~[MapTool.jar:1.15.0-beta.1]
	at net.rptools.maptool.client.TransferableHelper.importData(TransferableHelper.java:629) ~[MapTool.jar:1.15.0-beta.1]
	at java.desktop/javax.swing.TransferHandler.importData(Unknown Source) ~[?:?]
	at java.desktop/javax.swing.TransferHandler$DropHandler.drop(Unknown Source) ~[?:?]
	at java.desktop/java.awt.dnd.DropTarget.drop(Unknown Source) ~[?:?]
	at java.desktop/javax.swing.TransferHandler$SwingDropTarget.drop(Unknown Source) ~[?:?]
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source) ~[?:?]
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source) ~[?:?]
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source) ~[?:?]
	at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[?:?]
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[?:?]
	at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source) ~[?:?]
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(Unknown Source) [?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(Unknown Source) [?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source) [?:?]
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54) [MapTool.jar:1.15.0-beta.1]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source) [?:?]
2024-02-22 12:37:45.864 INFO  net.rptools.maptool.client.MapTool - Library rev.rptools.statsheets imported.

**Comment by bubblobill** [comment]
Ahh... whoops. Worked it out. Namespace conflict with built-in sheets
