### ISSUE TITLE
[Bug]: Setting Frame Rate Cap to 0 frazzles MapTool

### ISSUE THREAD

**Issue by Baaaaaz** [RPTools/maptool#4730]
### Describe the Bug

Discovered in testing https://github.com/RPTools/maptool/issues/4335 for 1.15.0-rc.2 but is a bug present in previous MapTool versions.

In 1.15.0-rc.2 typing `0` into the Frame Rate Cap field immediately raises an unexpected error (`java.lang.ArithmeticException: / by zero`)

In 1.13.2 and 1.14.3 typing `0` into the Frame Rate Cap does not raise this error immediately.

Furthermore, in all three versions once the Frame Rate Cap is set to 0 and you try to either: add a new map, restart MapTool, or load a campaign (from Windows explorer) you get a black map, the select map toolbar button breaks, and/or you get various java errors thrown at you. Fix is to reset Frame Rate Cap >0 and restart MapTool.

Similarly you can set the Frame Rate Cap to negative numbers or non-numerics, but did not appear to cause the same MapTool mayhem as setting it to 0.

### To Reproduce

1. Open MapTool.
2. Under: Edit Menu > Preferences > Application > Performance > Frame Rate Cap, type 0 (in 1.15.0-rc.2 an error is raised immediately).
4. Click Close on the error message.
5. Click OK to set the preference.
6. Create a new map (under: Map Menu - New Map... > OK) - observe black map and broken map selector.
7. Close MapTool and re-open - observe error message, black map, broken map selector, unable to open campaigns.

### Expected Behaviour

To only be able to enter sensible numbers into this field, without it breaking MapTool.

### Screenshots

Error message upon typing 0 into Frame Rate Cap in 1.15.0-rc.2
![image](https://github.com/RPTools/maptool/assets/131240480/82d9425a-0d70-46f5-a676-b3aeb07b041d)

Broken map selector (transparent and does not list any maps) after creating a new map:
![image](https://github.com/RPTools/maptool/assets/131240480/3323e5bf-fdfb-404d-910c-dfe730b90df0)

Error message No.1 on reopening MapTool:
![image](https://github.com/RPTools/maptool/assets/131240480/e4cd7d6e-c00d-4a9f-adcd-2c89e1950dda)

Error message No.2 on reopening MapTool:
![image](https://github.com/RPTools/maptool/assets/131240480/b154d3fd-250c-4187-aca4-680f3728fd8c)

### MapTool Info

1.13.2, 1.14.3, 1.15.0-rc.2

### Desktop

Windows 11

### Additional Context

Error in 1.15.0-rc.2 when typing 0 into Frame Rate Cap:
```
java.lang.ArithmeticException: / by zero
	at net.rptools.maptool.client.ui.zone.renderer.ZoneRenderer.setFrameRateCap(ZoneRenderer.java:230)
	at net.rptools.maptool.client.ui.preferencesdialog.PreferencesDialog$6.storeNumericValue(PreferencesDialog.java:943)
	at net.rptools.maptool.client.ui.preferencesdialog.PreferencesDialog$6.storeNumericValue(PreferencesDialog.java:937)
	at net.rptools.maptool.client.ui.preferencesdialog.PreferencesDialog$DocumentListenerProxy.updateValue(PreferencesDialog.java:1783)
	at net.rptools.maptool.client.ui.preferencesdialog.PreferencesDialog$DocumentListenerProxy.insertUpdate(PreferencesDialog.java:1766)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(Unknown Source)
	at java.desktop/javax.swing.text.PlainDocument.insertString(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.replace(Unknown Source)
	at java.desktop/javax.swing.text.JTextComponent.replaceSelection(Unknown Source)
	at java.desktop/javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyBinding(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyBindings(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.ui.preferencesdialog.PreferencesDialog.setVisible(PreferencesDialog.java:1515)
	at net.rptools.maptool.client.AppActions$14.executeAction(AppActions.java:664)
	at net.rptools.maptool.client.AppActions$ClientAction.execute(AppActions.java:3426)
	at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:3458)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

Error upon starting MapTool when Frame Rate Cap = 0:
```
java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.client.ui.zone.renderer.ZoneRenderer.getZone()" because the return value of "net.rptools.maptool.client.ui.MapToolFrame.getCurrentZoneRenderer()" is null
	at net.rptools.maptool.client.MapTool.postInitialize(MapTool.java:1377)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
Error on clicking Select Map toolbar icon after restarting MapTool with Frame Rate Cap = 0:
```
java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.server.ServerPolicy.getMapSelectUIHidden()" because the return value of "net.rptools.maptool.client.MapTool.getServerPolicy()" is null
	at net.rptools.maptool.client.ui.ZoneSelectionPopup.createEntries(ZoneSelectionPopup.java:48)
	at net.rptools.maptool.client.ui.ZoneSelectionPopup.<init>(ZoneSelectionPopup.java:36)
	at net.rptools.maptool.client.swing.SwingUtil$1.mousePressed(SwingUtil.java:363)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Baaaaaz** [comment]
Have tested this in 1.15.0-rc.3, and this bug is fixed by https://github.com/RPTools/maptool/pull/4732.  Thanks!
