### ISSUE TITLE
[Bug]: java.lang.UnsatisfiedLinkError: no glassgtk3

### ISSUE THREAD

**Issue by igorfranb** [RPTools/maptool#4839]
### Describe the Bug

I've just installed maptool and when I try to run it the message "java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib:/usr/lib"

### To Reproduce

Install Maptool and run it

### Expected Behaviour

The program should've run

### MapTool Info

Version: 1.14.3. Installion method: rpm file

### Desktop

OpenSuse Tumbleweed

### Additional Context

I've tried updating all packages, reinstalling JDK, but nothing works.

**Comment by kwvanderlinde** [comment]
Looks specific to a KDE install of Tumbleweed. I reproduced it on a fresh install, here's the underlying error:
<details>
<pre>
Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/kenneth/.openjfx/cache/20+19/amd64/libglassgtk3.so: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/kenneth/.openjfx/cache/20+19/amd64/libglassgtk3.so: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:221)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:200)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:247)
        at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:263)
        at net.rptools.maptool.client.swing.SplashScreen.<init>(SplashScreen.java:37)
        at net.rptools.maptool.client.MapTool.main(MapTool.java:1749)
        at net.rptools.maptool.client.LaunchInstructions.main(LaunchInstructions.java:51)

</pre>
</details>

So at least solution is simple:
```
sudo zypper install libgthread-2_0-0
```
Disclaimer: I'm not an OpenSuse person, no idea if that's the typical way to doing things.

What I don't know is whether there is anything we can do on our end to make this better, or whether this is just a limitation of JavaFX.

**Comment by Azhrei** [comment]
Since the `jpackage` installer only creates DEB files and RPM files for Debian and Red Hat, respectively, using those files on other OSes is covered by our blanket _caveat emptor_ policy. 😉

This has been commented on (in Discord) by folks using Arch Linux who need to either update their PATH or create symlinks in their `/usr/bin` directories because MT on Linux goes into `/opt`, and the simplistic approach taken by the converter that MT uses doesn't do this automatically.
