### ISSUE TITLE
Concurrent Modification Violation

### ISSUE THREAD

**Issue by kayila** [RPTools/maptool#489]
**Describe the bug**
A Concurrent violation exception popped up while I was dragging a token through a VBL area to mark fog of war as 'seen' while running Maptool 1.5.2 without the server running.

<details>
<summary>Stacktrace</summary>

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:937)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:891)
	at net.rptools.maptool.client.walker.AbstractZoneWalker.isWaypoint(AbstractZoneWalker.java:120)
	at net.rptools.maptool.client.walker.AbstractZoneWalker.getPath(AbstractZoneWalker.java:109)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.showBlockedMoves(ZoneRenderer.java:2104)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1266)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:798)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1313)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:857)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:840)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:840)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:815)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:764)
	at java.desktop/javax.swing.RepaintManager.access$1200(RepaintManager.java:69)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1880)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:43)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
</details>

**To Reproduce**
1. Open Maptool 1.5.2
2. Draw VBL for an area
3. Create a PC token on one side of the VBL
4. Under Map>Vision, select `Day`
5. Make sure Map>Fog of War is selected
6. Drag the token across the VBL area
7. `ConcurrentModificationViolation`!

**Expected behavior**
No concurrent violation exception should be thrown.

**Screenshots**
<details>
<summary>Map that threw the error</summary>

![image](https://user-images.githubusercontent.com/925235/59572133-0de40280-9079-11e9-916a-95f88509c4ff.png)
</details>

**MapTool Info**
- Version: 1.5.2
- Install: Jar version

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: Rolling

**Additional context**
<details>
<summary>Debug Info (Removed networking and user information)</summary>

```
==== MapTool Information ====
MapTool Version: 1.5.2
MapTool Home...: /home/kayila/.maptool
Max mem avail..: 2 GB
Max mem used...: 1 GB

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: /usr/lib/jvm/java-10-jdk
Java Version: 10.0.2

==== OS Information ====
OS Name........: Linux
OS Version.....: 4.19.36-1-MANJARO
OS Architecture: amd64
Number of Procs: 16

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1920x1080(-1)
Display 2: 1920x1080(-1)

==== Internet Gateway Devices ====
	No IGDs Found!
```
</details>

**Comment by duckinator** [comment]
I was able to reproduce this once, but can't _consistently_ reproduce it. Going to poke around a bit more.

**Comment by Phergus** [comment]
See also #328 

These are probably related:
- Sentry Issue: [MAPTOOL-5C](https://sentry.io/organizations/rptools/issues/950088632/?referrer=github_integration)
- Sentry issue: [MAPTOOL-ED](https://sentry.io/organizations/rptools/issues/976063283/?referrer=github_integration)
- Sentry Issue: [MAPTOOL-169](https://sentry.io/organizations/rptools/issues/1069977964/?referrer=github_integration)
