### ISSUE TITLE
Add "isHostingServer" and "gmRevealsVision " to getInfo("server") results

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#663]
**Is your feature request related to a problem? Please describe.**
Add the Hosting a Server status to the getInfo("server") results.
Same for the new server setting, GM Reveals Vision... (see #665)

**Describe the solution you'd like**
Add "hosting server" and "GM reveals vision for unowned tokens" to the JSON result from getInfo("Server")

**Comment by JamzTheMan** [comment]
thanks :)

**Comment by Phergus** [comment]
@JamzTheMan  Also needs getInfoFunction.java updated so that those settings show up in the returned JSON.

**Comment by JamzTheMan** [comment]
Ah ok. I incorrectly assumed it was using the raw json that was returned here but couldn't test it because the parser died in dev. :(

**Comment by Phergus** [comment]
I have no problem running from develop with gradlew run, using the uberJar or just launching from the project in Netbeans.  Macros work just fine for me.

**Comment by JamzTheMan** [comment]
I still get this:

```java.lang.NoClassDefFoundError: net/rptools/parser/ExpressionLexer
	at net.rptools.parser.Parser.parseExpression(Parser.java:251)
	at net.rptools.common.expression.ExpressionParser.evaluate(ExpressionParser.java:214)
	at net.rptools.maptool.client.MapToolLineParser.parseExpression(MapToolLineParser.java:1490)
	at net.rptools.maptool.client.MapToolLineParser.parseLine(MapToolLineParser.java:1298)
	at net.rptools.maptool.client.MapToolLineParser.parseLine(MapToolLineParser.java:711)
	at net.rptools.maptool.client.macro.MacroManager.executeMacro(MacroManager.java:177)
	at net.rptools.maptool.client.ui.commandpanel.CommandPanel.commitCommand(CommandPanel.java:511)
	at net.rptools.maptool.client.ui.commandpanel.CommandPanel.commitCommand(CommandPanel.java:448)
	at net.rptools.maptool.client.AppActions$39.execute(AppActions.java:1468)
	at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:3044)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2948)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6366)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:871)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1140)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1010)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:836)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4847)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:43)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: net.rptools.parser.ExpressionLexer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 47 more
```

But i've cleared my gradle cache and and such to debug parser issue, let me test some more...

**Comment by JamzTheMan** [comment]
OK, so moving on (problem resolved)...

Why does getInfoFunction.getServerInfo() not just use MapTool.getServerPolicy().toJSON()??

Just to add this? and why?
```
InitiativePanel ip = MapTool.getFrame().getInitiativePanel();
    if (ip != null) {
      sinfo.put(
          "initiative owner permissions",
          ip.isOwnerPermissions() ? BigDecimal.ONE : BigDecimal.ZERO);
    }
```

**Comment by Phergus** [comment]
I'm guessing because originally it didn't include all of the server info and/or because Craig wanted to put his own tag names in there to be more user friendly.

**Comment by JamzTheMan** [comment]
Question is, should init panel stuff really be in server info?

Seems like it was show horned there vs it's own or...?

**Comment by Phergus** [comment]
I wouldn't think it should be but there really isn't another getInfo() category that makes more sense.  I don't even know where that setting is at.

**Comment by JamzTheMan** [comment]
I will see if they can be combined in a smarter way.

**Comment by Phergus** [comment]
@JamzTheMan  Status?

**Comment by Phergus** [comment]
Changing getInfo("server") function to pull the JSON object right from ServerPolicy instead of duplicating code already in ServerPolicy.

**Comment by JamzTheMan** [comment]
ya, still gotta do that...

**Comment by Phergus** [comment]
Code's done.  Just waiting for the CI dust to settle and I'll commit it.

**Comment by JamzTheMan** [comment]
cool cool go ahead and I can review it and merge

**Comment by Phergus** [comment]
Wiki updated.

**Comment by Phergus** [comment]
Issue complete.
