### ISSUE TITLE
Error when closing maptool

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#700]
**Describe the bug**
The following error shows up in the console when closing Maptool with a macro editing window opened:

```
(MapToolEventQueue.java:51) [AWT-EventQueue-0] ERROR net.rptools.maptool.client.swing.MapToolEventQueue - java.lang.NullPointerException
java.lang.NullPointerException: null
        at net.rptools.maptool.client.ui.MacroButtonDialog.destroyMenuBar(MacroButtonDialog.java:553) ~[main/:?]
        at net.rptools.maptool.client.ui.MacroButtonDialog.access$000(MacroButtonDialog.java:84) ~[main/:?]
        at net.rptools.maptool.client.ui.MacroButtonDialog$1.windowClosed(MacroButtonDialog.java:148) ~[main/:?]
        at java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:368) ~[?:?]
        at java.awt.Window.processWindowEvent(Window.java:2081) ~[?:?]
        at javax.swing.JDialog.processWindowEvent(JDialog.java:686) ~[?:?]
        at java.awt.Window.processEvent(Window.java:2037) ~[?:?]
        at java.awt.Component.dispatchEventImpl(Component.java:4966) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2319) ~[?:?]
        at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4798) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
        at java.awt.EventQueue.access$600(EventQueue.java:97) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
        at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:43) [main/:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

**Comment by Merudo** [comment]
PR #701 should fix this.

**Comment by Phergus** [comment]
@Merudo  Did you have reliable steps to reproduce this?  Could not reproduce with 1.5.3 or 1.5.4.  Was this only when launched from IDE?

**Comment by Merudo** [comment]
Yes, only when launched from IDE or from command prompt (`gradlew run`).

**Comment by Phergus** [comment]
Thanks. Got it.

Tested.  Exception no longer appears.
