### ISSUE TITLE
Null Pointer Exception when selecting "New Map" in library

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#740]
**Describe the bug**
Right clicking "New Map" in the library generates a null pointer exception. Full text of the exception:

```jave
java.lang.NullPointerException
	at net.rptools.maptool.client.ui.MapToolFrame$11.createZone(MapToolFrame.java:1384)
	at net.rptools.maptool.client.ui.MapToolFrame$11.access$1200(MapToolFrame.java:1343)
	at net.rptools.maptool.client.ui.MapToolFrame$11$1.actionPerformed(MapToolFrame.java:1375)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:43)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1. Start new campaign
2. Right click on the background of the resource library, such as in-between tokens
3. Pick "New Map"
4. See null exception error.

**Expected behavior**
No error. And probably no option to create a new map either.

**Screenshots**
![newMap](https://user-images.githubusercontent.com/7371085/65457011-3b76df80-de10-11e9-8b9a-cdaf9afa22fd.png)

**MapTool Info**
- Version: 1.5.0 to 1.5.4, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Dates back to 1.4.0.5 and possible older.

**Comment by JamzTheMan** [comment]
@pnichols04 Was just in this code (not blaming!), this is probably a quick(ish) fix, no?

I'm guessing the right click event is fired on the top level component vs on the sub component.

Unless @Merudo you are working on this already?

**Comment by Merudo** [comment]
I'm not working on this. I'm not at alll familiar with the library panel.

**Comment by pnichols04** [comment]
I notice that no asset is actually selected in the image.

MapToolFrame.java(1360ff):
```List<Object> idList = panel.getSelectedIds();
              if (idList == null || idList.size() == 0) {
                return;
              }
              final int index = (Integer) idList.get(0);
...
                        public void actionPerformed(ActionEvent e) {
                          createZone(panel.getAsset(index));
                                           ^^^^^^^^
                        }```

With nothing selected, idList *should* be an empty list, so the function *should* be bailing out.  But it gets to the createZone() call, and it looks like it ends up with a null from getAsset().

I'll try stepping through it, but I might not be able to get to it until later this week.

**Comment by Phergus** [comment]
Yup.  This has been there forever.  It happens when you don't have an image selected.

**Comment by Azhrei** [comment]
While you’re in there (a general entreaty to anyone planning to make code changes), please change code snippets that say `something.size()==0` into `something.isEmpty()`.  Just a pet peeve, but the latter is best practice when working with collections.  (Can be much faster for _some_ containers; not sure about in the latest Java, though.) 🙂

**Comment by JamzTheMan** [comment]
I always liked the cleaner isEmpty usage as well :)

@pnichols04 thanks for looking at it and no hurry, it's been around for awhile.

If you would like, go ahead and see if you can assign this issue to yourself? Mostly I just want to see if you guys can do that now with the new permissions.

**Comment by pnichols04** [comment]
> If you would like, go ahead and see if you can assign this issue to yourself? Mostly I just want to see if you guys can do that now with the new permissions.

Negative.  It's not showing me the assignment controls.

**Comment by JamzTheMan** [comment]
Well thats a bummer... Not on a phone are you? I currently am and I don't have them either unless I go into desktop site. :(

Be nice if you guys could claim issue you want to work on is all.

**Comment by pnichols04** [comment]
> Not on a phone are you? 

Nope.

> Be nice if you guys could claim issue you want to work on is all.

Yup.

**Comment by Phergus** [comment]
Needs testing.

**Comment by JamzTheMan** [comment]
Looks good, I only get the menu option now when actually clicking an image.
