### ISSUE TITLE
PDF Extraction not working for JPEG2000 embedded images

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#751]
**Describe the bug**
PDF Extract is not extracting any images that are jpeg2000 embedded inside PDF's (png and jpg should extract, although jpeg2000 is more commonly used)

```
org.apache.pdfbox.filter.MissingImageReaderException: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
        at org.apache.pdfbox.filter.Filter.findImageReader(Filter.java:163)
        at org.apache.pdfbox.filter.JPXFilter.readJPX(JPXFilter.java:92)
        at org.apache.pdfbox.filter.JPXFilter.decode(JPXFilter.java:58)
        at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:77)
        at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:175)
        at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:163)
        at org.apache.pdfbox.pdmodel.common.PDStream.createInputStream(PDStream.java:236)
        at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.<init>(PDImageXObject.java:140)
        at org.apache.pdfbox.pdmodel.graphics.PDXObject.createXObject(PDXObject.java:70)
        at org.apache.pdfbox.pdmodel.PDResources.getXObject(PDResources.java:426)
        at net.rptools.maptool.util.ExtractImagesFromPDF.getImagesFromResources(ExtractImagesFromPDF.java:178)
        at net.rptools.maptool.util.ExtractImagesFromPDF.extractPage(ExtractImagesFromPDF.java:157)
        at net.rptools.maptool.client.ui.assetpanel.ImageFileImagePanelModel$ExtractImagesTask.call(ImageFileImagePanelModel.java:456)
        at net.rptools.maptool.client.ui.assetpanel.ImageFileImagePanelModel$ExtractImagesTask.call(ImageFileImagePanelModel.java:443)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**To Reproduce**
1. Add PDF with jpeg2000 images to Asset Library
2. Check logs for error messages when extracting
3. (may need to run from the uberJAR to see messages, running from IDE does not produce the error)

**Expected behavior**
All images should be extracted and shown

**MapTool Info**
- Version: 1.5.5
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Tested with 1.5.5-rc.2.  Works again with JPEG2000 images embedded in PDFs.  Closing.
